### ISSUE TITLE
mTLS certificate validation fails due to invalid wildcard in "subjectAltName" extension

### ISSUE THREAD

**Issue by stippi** [yugabyte/yugabyte-db#10329]
We have installed YugabyteDB on GKE clusters via Helm following [these instructions](https://docs.yugabyte.com/latest/deploy/kubernetes/multi-cluster/gke/helm-chart/). We enabled mTLS with these Helm values:

```
[...]

tls:
  enabled: true
  nodeToNode: true
  certManager:
    enabled: true

gflags:
  master:
    placement_cloud: "gke"
    placement_region: "europe-west1"
    placement_zone: "europe-west1-b"
    leader_failure_max_missed_heartbeat_periods: 10
  tserver:
    placement_cloud: "gke"
    placement_region: "europe-west1"
    placement_zone: "europe-west1-b"
    leader_failure_max_missed_heartbeat_periods: 10
    ysql_hba_conf_csv: "hostssl all all all cert"
```

When trying to connect to the T-Server via mTLS from a self-written test client based on node.js, the following error is given:

```
Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: yb-tservers.yb-demo-europe-west1-b.svc.cluster.local. is not in the cert's altnames: DNS:*.*.yb-demo-europe-west1-b, DNS:*.*.yb-demo-europe-west1-b.svc.cluster.local
    at new NodeError (node:internal/errors:371:5)
    at Object.checkServerIdentity (node:tls:297:12)
    at TLSSocket.onConnectSecure (node:_tls_wrap:1540:27)
    at TLSSocket.emit (node:events:390:28)
    at TLSSocket._finishInit (node:_tls_wrap:944:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:725:12) {
  reason: "Host: yb-tservers.yb-demo-europe-west1-b.svc.cluster.local. is not in the cert's altnames: DNS:*.*.yb-demo-europe-west1-b, DNS:*.*.yb-demo-europe-west1-b.svc.cluster.local",
  host: 'yb-tservers.yb-demo-europe-west1-b.svc.cluster.local',
  cert: {
    subject: [Object: null prototype] {
      CN: 'yb-tserver-0.yb-tservers.yb-demo-europe-west1-b.svc.cluster.local'
    },
    issuer: [Object: null prototype] { CN: 'Yugabyte DB' },
    subjectaltname: 'DNS:*.*.yb-demo-europe-west1-b, DNS:*.*.yb-demo-europe-west1-b.svc.cluster.local',
    [...]
```

Trying to connect via the plain `psql` tool with a copy of the certificate, a similar error is printed:

```
psql: error: server certificate for "*.*.yb-demo-europe-west1-b" (and 1 other name) does not match host name "yb-tserver-0.yb-tservers.yb-demo-europe-west1-b.svc.cluster.local"
```

However, connecting with the [`ysqlsh` CLI](
https://docs.yugabyte.com/latest/deploy/kubernetes/clients/#connect-from-within-the-kubernetes-cluster), it works.

We have tried to dig into the issue and found that [double wildcards](https://github.com/yugabyte/charts/blob/b64b110df80aecbc47bdda80f231b018873eb3f7/stable/yugabyte/templates/service.yaml#L45) are forbidden for entries in the `subjectAltNames` array. Could you please clarify how this is supposed to work, and whether the ysqlsh client contains any magic to allow for double wildcards?
