### ISSUE TITLE
[YSQL][Driver] Yugabyte Smart Driver should work with Spring Boot autoconfiguration and embedded database

### ISSUE THREAD

**Issue by ssherwood** [yugabyte/yugabyte-db#10607]
### Description

Currently, the JDBC smart driver cannot be used with a vanilla Spring Boot application.  The classes as loaded don't automatically activate the data source initializer:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class
```

If you attempt to specify the driver/

```
spring:
  datasource:
    url: jdbc:yugabytedb://127.0.0.1:5433/yugabyte
    username: yugabyte
    driver-class-name: com.yugabyte.Driver
    type: com.yugabyte.ysql.YBClusterAwareDataSource
```

Then the Hikari connection pool is not activated.

If you try to activate the Hikari connection pool, then it errors:

```
2021-11-16 11:21:34.030 ERROR 161627 --- [           main] com.zaxxer.hikari.HikariConfig           : HikariPool-1 - cannot use driverClassName and dataSourceClassName together.
```
If you just specify the driver... then load balancing doesn't work.

There appears to be some set of missing configuration(s) that need to be applied to activate the driver, datasource and connection pool properly?

Thanks.

**Comment by ssherwood** [comment]
A quick update.  I *think* I found a way to get it working with these custom configs:

```java
    @Bean
    @ConfigurationProperties(prefix = "spring.datasource.hikari")
    public HikariConfig hikariConfig() {
        return new HikariConfig();
    }

    @Bean
    @Primary
    public DataSource dataSource() {
        return new HikariDataSource(hikariConfig());
    }
```

This manually overrides the Spring datasource autoconfigs, so you don't use any of those configs.  My application.yml looks like this:

```yml
spring:
  jpa:
    open-in-view: false
  datasource:
    hikari:
      username: yugabyte
      data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
      data-source-properties:
        serverName: 127.0.0.1
        portNumber: 5433
        databaseName: yugabyte
        additionalEndpoints: 127.0.0.2:5433,127.0.0.3:5433
        topologyKeys: "cloud1.datacenter1.rack1"
```

This looks to be creating connections in the Hikari pool that connect to the three different nodes I have:

```
2021-11-17 11:01:37.776 DEBUG 349979 --- [nnection thread] com.yugabyte.Driver                      : TopologyAwareLoadBalancer: Refresh not required.
2021-11-17 11:01:37.777 DEBUG 349979 --- [onnection adder] com.yugabyte.ds.common.BaseDataSource    : Created a Non-Pooling DataSource from PostgreSQL JDBC Driver 42.3.0 for yugabyte at jdbc:yugabytedb://127.0.0.1,127.0.0.2:5433,127.0.0.3:5433/yugabyte?loginTimeout=30&load-balance=true&topology-keys=cloud1.datacenter1.rack1
2021-11-17 11:01:37.777 DEBUG 349979 --- [onnection adder] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection com.yugabyte.jdbc.PgConnection@16b5c4be
```

Obviously, the goal should be that the Yugabyte JDBC URL is properly recognized by Spring Boot on startup and this is all autoconfigured as it would be for any other database that Spring Boot supports.
