### ISSUE TITLE
[YSQL] t-server Unknown Cause Segmentation Fault

### ISSUE THREAD

**Issue by ColaIan** [yugabyte/yugabyte-db#12626]
### Description

Docker Log:
```
yb-tserver-n1 | 2022-05-24 03:43:09.203 UTC [45] LOG:  YugaByte is ENABLED in PostgreSQL. Transactions are enabled.
yb-tserver-n1 | 2022-05-24 03:43:09.208 UTC [45] LOG:  pgaudit extension initialized
yb-tserver-n1 | 2022-05-24 03:43:09.210 UTC [45] LOG:  listening on IPv4 address "172.19.0.3", port 5433
yb-tserver-n1 | 2022-05-24 03:43:09.212 UTC [45] LOG:  listening on Unix socket "/tmp/.yb.4439665844579941977/.s.PGSQL.5433"
yb-tserver-n1 | 2022-05-24 03:43:09.226 UTC [45] LOG:  redirecting log output to logging collector process
yb-tserver-n1 | 2022-05-24 03:43:09.226 UTC [45] HINT:  Future log output will appear in directory "/mnt/tserver/yb-data/tserver/logs".
yb-tserver-n1 | *** Aborted at 1653366702 (unix time) try "date -d @1653366702" if you are using GNU date ***
yb-tserver-n1 | PC: @                0x0 (unknown)
yb-tserver-n1 | *** SIGSEGV (@0x0) received by PID 7 (TID 0x7fc392cbd700) from PID 0; stack trace: ***
yb-tserver-n1 |     @     0x7fc39c961120 (unknown)
yb-tserver-n1 |     @          0x352a685  yb::tablet::AbstractTablet::HandlePgsqlReadRequest()
yb-tserver-n1 |     @          0x355de9b  yb::tablet::Tablet::HandlePgsqlReadRequest()
yb-tserver-n1 |     @          0x36b3a8a  yb::tserver::(anonymous namespace)::ReadQuery::Complete()
yb-tserver-n1 |     @          0x36eb1a0  yb::tserver::TabletServiceImpl::Read()
yb-tserver-n1 |     @          0x37a5af2  std::__1::__function::__func<>::operator()()
yb-tserver-n1 |     @          0x37a72c5  yb::tserver::TabletServerServiceIf::Handle()
yb-tserver-n1 |     @          0x34dc2da  yb::rpc::ServicePoolImpl::Handle()
yb-tserver-n1 |     @          0x349b1e4  yb::rpc::InboundCall::InboundCallTask::Run()
yb-tserver-n1 |     @          0x34e9a64  yb::rpc::(anonymous namespace)::Worker::Execute()
yb-tserver-n1 |     @          0x3849fca  yb::Thread::SuperviseThread()
yb-tserver-n1 |     @     0x7fc39c512694 start_thread
yb-tserver-n1 |     @     0x7fc39ca1441d __clone
yb-tserver-n1 exited with code 139
```
Server Info:
```
OS: Ubuntu VPS, Docker
Total Memory: 29.4G
CPU: AMD EPYC 7282, Using 8 out of 16-Cores
SSD: 391G total, 78G available
```
Docker Compose File
```yml
version: '2'

services:
  yb-master:
      image: yugabytedb/yugabyte:latest
      container_name: yb-master-n1
      restart: always
      volumes:
      - ./yb-master:/mnt/master
      command: [ "/home/yugabyte/bin/yb-master",
                "--fs_data_dirs=/mnt/master",
                "--master_addresses=yb-master-n1:7100",
                "--rpc_bind_addresses=yb-master-n1:7100",
                "--replication_factor=1"]
      ports:
      - "7000:7000"
      environment:
        SERVICE_7000_NAME: yb-master

  yb-tserver:
      image: yugabytedb/yugabyte:latest
      container_name: yb-tserver-n1
      restart: always
      volumes:
      - ./yb-tserver:/mnt/tserver
      command: [ "/home/yugabyte/bin/yb-tserver",
                "--fs_data_dirs=/mnt/tserver",
                "--start_pgsql_proxy",
                "--rpc_bind_addresses=yb-tserver-n1:9100",
                "--tserver_master_addrs=yb-master-n1:7100"]
      ports:
      - "9042:9042"
      - "5433:5433"
      - "9000:9000"
      environment:
        SERVICE_5433_NAME: ysql
        SERVICE_9042_NAME: ycql
        SERVICE_6379_NAME: yedis
        SERVICE_9000_NAME: yb-tserver
      depends_on:
      - yb-master
```

Core dump:
Privately provided to @ddorian on Slack due to it possibly containing sensitive information
