### ISSUE TITLE
Configurable annotations on YW loadbalancer

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#1338]
In order to keep the yugaware UI on an internal LB, I need to add the following annotations to any `Service: LoadBalancer`:

```yml
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

Using `yugaware-1.0.0.tgz` from May 9th, there is currently not a way to add those annotations to yugaware from the `values.yml`. I resolved this by untaring the chart and adding the following to the `yugaware-ui` service:

```yml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-yugaware-ui
  labels:
    app: {{ .Release.Name }}-yugaware
    chart: {{ template "yugaware.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

# This is the part I added:
  annotations:
    {{- range $key, $value := .Values.web.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
# etc...
```

and including this in my `values.yml`:

```yml
web:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

It's preferable to have these configurable out of the box than manually modifying the chart.

Thanks for your time

/cc @xyloman @dashaun @ajcaldera1

**Comment by ramkumarvs** [comment]
This is implemented as it is available as part of helm chart version `1.3.2` of yugaware

**Comment by aegershman** [comment]
https://github.com/YugaByte/charts/blob/master/stable/yugaware/templates/service.yaml#L15

Will test but I believe this is indented too far. `annotations` ends up under `labels`, but it should be at the same level as `labels`

for example if you were to use these `values.yml`:

```
yugaware:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

the service ends up looking like this:

```
apiVersion: v1
kind: Service
metadata:
  name: yugaware-yugaware-ui
  labels:
    app: yugaware-yugaware
    chart: yugaware
    release: yugaware
    heritage: Tiller
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
```

which I don't think validates. let me test though.
