### ISSUE TITLE
[YW][k8s] helm chart validation error on configmaps

### ISSUE THREAD

**Issue by aegershman** [YugaByte/yugabyte-db#1398]
Using helm 2.14.0; tried to install yw-1.0.0 chart, and got the following validation error:

```
Release "yugaware" does not exist. Installing it now.
Error: validation failed: error validating "": error validating data: [ValidationError(StatefulSet.spec.template.spec.volumes[4].configMap): unknown field "release" in io.k8s.api.core.v1.ConfigMapVolumeSource, ValidationError(StatefulSet.spec.template.spec.volumes[5].configMap): unknown field "release" in io.k8s.api.core.v1.ConfigMapVolumeSource]
```

If we take a look in `yugaware/templates/service.yml` we see this:

```yml
spec:
  serviceName: {{ .Release.Name }}-yugaware
  replicas: {{ .Values.yugaware.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-yugaware
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-yugaware
    spec:
      serviceAccountName: {{ .Release.Name }}
      imagePullSecrets:
      - name: {{ .Values.image.pullSecret }}
      volumes:
        - name: yugaware-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-yugaware-storage
        - name: yugaware-ui
          emptyDir: {}
        - name: thirdparty-deps
          emptyDir: {}
        - name: prometheus-storage
          emptyDir: {}
        - name: yugaware-config
          configMap:
            name: {{ .Release.Name }}-yugaware-app-config
            release: {{ .Release.Name }}
            items:
              - key: application.docker.conf
                path: application.docker.conf
```

notice the `configMap`'s have a `release:` key, which [I don't think has `release` as a valid subkey under it?](https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1_configmapvolumesource)

I'm not sure if this is an issue which is a bug in [helm-2.14.0, possibly because of this issue](https://github.com/helm/helm/commit/32d7f1a3fc226c1745a58b51e318b7362bc7a0bf), or if it's a minor hiccup in the chart & it wasn't caught until something happened with manifest validation in 2.14.0...?

Thanks for your time
