### ISSUE TITLE
[DocDB][Perf][m6i.large][Sysbench][oltp_multi_ins] observed compaction thread utilising fare amount amount of CPU causing failure of LOAD phase .

### ISSUE THREAD

**Issue by mangesh-at-yb** [yugabyte/yugabyte-db#16031]
### Description

While comparing table limits between YB-colocated database Vs YB-normal database, observed high CPU utilisation on Leader node for that colocated db with 250 tables, flame-graphs shown "Priority-worker" kicks in and consumes CPU, hence sysbench LOAD phase fails with RPC timeout. But this behaviour has not observed with Non-colocated db, sysbench LOAD phase completes without errors and completes whole workload.

### Setup:

- Three **m6i.large** nodes, RF=3 cluster running with YB version: **2.17.2.0-b90**

- Below gFalgs set : 
```
        masterGFlags:
          - "name": "enable_automatic_tablet_splitting"
            "value": true
          - "name": "ysql_enable_packed_row"
            "value": true
          - "name": "default_memory_limit_to_ram_ratio"
            "value": 0.15
          - "name": "ysql_max_connections"
            "value": 4096
        tserverGFlags:
          - "name": "enable_automatic_tablet_splitting"
            "value": true
          - "name": "ysql_enable_packed_row"
            "value": true
          - "name": "default_memory_limit_to_ram_ratio"
            "value": 0.65
          - "name": "db_block_cache_size_percentage"
            "value": 50
          - "name": "ysql_max_connections"
            "value": 4096
```
### Steps:

- Clone sysbench and build sysbench on one of the client machines. 
```
git clone  https://github.com/yugabyte/sysbench.git
```
- Configure node=3 and RF=3 YB-Cluster with said gFlags.

- Create colocated database, which will be used during entire workload.
```
~yugabyte/tserver/bin/ysqlsh -h <YB-Node> -p 5433 -U yugabyte 
Password for user yugabyte: 
ysqlsh (11.2-YB-2.17.2.0-b0)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

yugabyte=# create database colodb with colocated=true;

```
- **Execute below commands  from client machine :** 

- Cleanup: ( if cluster has used previously )

```
./src/sysbench ./src/lua/oltp_multi_insert.lua --table_size=500000 --manual_range_splitting=false --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=250 --pgsql-db=colodb --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=60 --time=180 --pgsql-password=Password321! --db-driver=pgsql --pgsql-port=5433 --pgsql-host=<YB_NODES> --threads=1 cleanup;
```
- CREATE phase:  
```
./src/sysbench ./src/lua/oltp_multi_insert.lua --table_size=500000 --manual_range_splitting=false --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=250 --pgsql-db=colodb --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=60 --time=180 --pgsql-password=Password321! --db-driver=pgsql --pgsql-port=5433 --pgsql-host=<YB_NODES> --threads=1 create;
```

- Get leader, using "yb_stats" command from lates yb_stats : https://github.com/fritshoogland-yugabyte/yb_stats/releases/download/v0.9.3/yb_stats-0.9.3-1.el7.x86_64.rpm 

```
yb_stats --hosts <YB_NODES> --get-coloc-leader-host colodb
```
- LOAD phase:  Which consumes CPU and fails with RPC timeout.
```
./src/sysbench ./src/lua/oltp_multi_insert.lua --table_size=500000 --manual_range_splitting=false --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=250 --pgsql-db=colodb --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=60 --time=180 --pgsql-password=Password321! --db-driver=pgsql --pgsql-port=5433 --pgsql-host=<YB_LEADER_NODE> --threads=2 load;
```

- Repeat same steps with Non-colocated database, by specifying all three YB_NODES and LOAD threads set to 6

### Observed: 

- 100% CPU utilisation on YB-Leader node and after loading some tables, sysbench gives below RPC timeout error for one of the INSERT query in LOAD phase.
```
"FATAL: PQexec() failed: 7 Timed out: Perform RPC (request call id 3636) to 172.151.21.120:9100 timed out after 120.000s", 
```
- Flame graph shown "Priority-worker" thread kicks in, incase of Colocated db and consumes 100% CPU.

- Also tried setting up "rocksdb_level0_file_num_compaction_trigger=20", apart from decrease in CPU% for "Priority-worker" no major difference observed.

- With Non-colocated db, sysbench completes LOAD phase and executes RUN phase successfully, used below LOAD phase cmd for Non-colocated db: Watch for "--pgsql-host=<YB_NODES>" and "--threads=6", specify all three YB nodes.
```
./src/sysbench ./src/lua/oltp_multi_insert.lua --table_size=500000 --manual_range_splitting=false --range_selects=false --pgsql-user=yugabyte --range_size=1000 --index_updates=10 --tables=250 --pgsql-db=colodb --warmup-time=600 --point_selects=10 --serial_cache_size=1000 --create_secondary=false --range_key_partitioning=true --non_index_updates=10 --thread-init-timeout=60 --time=180 --pgsql-password=Password321! --db-driver=pgsql --pgsql-port=5433 --pgsql-host=<YB_NODES> --threads=6 load;
```

### Expected 

- Need to tune compaction  in case of Colocated database, which will not consume more CPU and cause the failures. 

### Extra info :
- Flame-graph analysis:

<img width="1125" alt="Screenshot 2023-02-08 at 4 13 32 PM" src="https://user-images.githubusercontent.com/98325393/217507611-36a27fc1-521a-4d1d-aaa0-4ab24f5e45db.png">

- Flame graphs:
**colo-db-compaction-setto-20** 
![colo-db-compaction-setto-20](https://user-images.githubusercontent.com/98325393/217507788-d5970d59-bdcf-4404-a6bd-c8ec62439e85.svg)
**colo-db-default-compaction-setting**
![colo-db-default-compaction-setting](https://user-images.githubusercontent.com/98325393/217507797-693ef490-ba03-4bb8-b204-4125541dd4a8.svg)
**non-colo-db-default-compaction-setting**
![non-colo-db-default-compaction-setting](https://user-images.githubusercontent.com/98325393/217507804-11b0f475-daf1-4101-ad1d-6f0e9ec14b66.svg)
