### ISSUE TITLE
[DocDB] Index backfill takes too long

### ISSUE THREAD

**Issue by WhiteWind** [yugabyte/yugabyte-db#16340]
Jira Link: [DB-5760](https://yugabyte.atlassian.net/browse/DB-5760)
### Description

Yugabyte 2.17.0.0-b24

Query 
```
CREATE UNIQUE INDEX CONCURRENTLY vp_2023_03_unique_value
    ON public.vp_2023_03 (object_id, param_id, device_time, value)
```
Had been running for 40 minutes:

Job Name | State | Start Time | Duration | Description
-- | -- | -- | -- | --
kComplete | 41.7 min ago | 40.7 min | Backfilling { vp_2023_03_unique_value } Done

Table size (it's a partition):
Total: 261.60M
WAL Files: 128.00M
SST Files: 133.60M
SST Files Uncompressed: 480.42M

Rows in table: 1.4M

Average/Max disk read was 4/15 MBytes/s
Average/Max disk write was 1/6 MBytes/s

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-5760]: https://yugabyte.atlassian.net/browse/DB-5760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by ddorian** [comment]
@WhiteWind 

What is the cluster size, configuration, and hardware used (memory,CPU,ssd/disk)?

What's the CPU usage during this time & cluster load?

**Comment by WhiteWind** [comment]
It's single-node docker cluster inside VM on HDD, 2 cores of Core i7-3770 CPU @ 3.40GHz, 8G ram: 
```
  yugabyte-master:
    image: "yugabytedb/yugabyte:2.17.0.0-b24"
    ports:
      - "7000:7000"
      - "7100:7100"
    expose:
      - 7000
      - 7100
    volumes:
      - ./yb_data:/yb_data
    command:
      - "/home/yugabyte/bin/yb-master"
      - "--fs_data_dirs=/yb_data"
      - "--logtostderr"
      - "--replication_factor=1"
      - "--enable_automatic_tablet_splitting=true"
      - "--rpc_bind_addresses=0.0.0.0:7100"
      - "--webserver_port=7000"
      - "--master_addresses=yugabyte-master:7100"
      - "--server_broadcast_addresses=yugabyte-master"
  yugabyte:
    image: "yugabytedb/yugabyte:2.17.0.0-b24"
    ports:
      - "9000:9000"
      - "9100:9100"
      - "5433:5433"
      - "13000:13000"
    expose:
      - 5433
      - 9000
      - 9100
      - 13000
    volumes:
      - ./yb_data:/yb_data
    depends_on:
      - yugabyte-master
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/yb_data"
      - "--start_pgsql_proxy"
      - "--ysql_request_limit=65535"
      - "--yb_enable_read_committed_isolation=true"
      - "--ysql_log_statement=ddl"
      - "--ysql_enable_packed_row=true"
      - "--ysql_request_limit=65536"
      - "--ysql_log_min_duration_statement=500"
      - "--logtostderr"
      - "--webserver_port=9000"
      - "--rpc_bind_addresses=0.0.0.0:9100"
      - "--pgsql_proxy_bind_address=0.0.0.0:5433"
      - "--server_broadcast_addresses=yugabyte"
      - "--tserver_master_addrs=yugabyte-master:7100"
```
