### ISSUE TITLE
Operator for YugaByte proposal

### ISSUE THREAD

**Issue by vishal-biyani** [yugabyte/yugabyte-db#1710]
This issue documents some early thoughts and design of an operator for YugaBute DB.

For YugaByte DB operator - we will need to design a Custom Resource Definition (CRD) and write corresponding controllers. The CRD can be used by the user to create custom resources (CR)

A universe in YugaByte DB is a set of one more or more clusters. These clusters can span one region (One Kubernetes clusters) or multiple regions (multiple Kubernetes clusters). A CRD definition currently only spans one cluster (There are efforts around federation across clusters and multi-cluster use cases - but they are in early stage). So for the purpose of this discussion, we will focus on a universe which spans in a single region but can have multiple clusters.

We will have a single CRD for Universe and a sample universe definition is written below. 

- A universe CR can have multiple clusters defined, one of them will be primary and others will be read replicas
- The universe of multiple clusters will still be limited to one Kubernetes cluster (And it is assumed that one Kubernetes cluster spans in a single region)

```
apiVersion: yb.db.com/v1beta1
kind: universe.yugabytedb.com
metadata:
 name: my-first-ybdb-cluster
spec:
  clusters:
  - cluster1:
      name: firstcluster
      primary: true
      storage:
        master:
            count: 2
            size: 10Gi
            storageClass: standard
        tserver:
            count: 2
            size: 10Gi
            storageClass: standard
  - cluster2
      name: secondcluster
      primary: false
      storage:
        master:  
  
```
