### ISSUE TITLE
[yugabyted] Correct `placement_uuid` not being set while deploying a 3-node cluster.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#19314]
### Description

Start a 3-node cluster using the following `docker-compose.yaml`:
```
services:
  yugabyted-0:
    container_name: yugabyted-0
    hostname: yugabyted-0
    image: yugabytedb/yugabyte:latest
    platform: linux/amd64
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false
#      bin/yugabyted configure data_placement --constraint_value=cloud.region.zone1 --fault_tolerance=zone --rf=3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "15433:15433"
  yugabyted-1:
    container_name: yugabyted-1
    hostname: yugabyted-1
    image: yugabytedb/yugabyte:latest
    platform: linux/amd64
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false --join=yugabyted-0
#      bin/yugabyted configure data_placement --constraint_value=cloud.region.zone2 --fault_tolerance=zone --rf=3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7001:7000"
      - "9001:9000"
      - "5434:5433"
    depends_on:
      - yugabyted-0
  yugabyted-2:
    container_name: yugabyted-2
    hostname: yugabyted-2
    image: yugabytedb/yugabyte:latest
    platform: linux/amd64
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --fault_tolerance=zone --tserver_flags="ysql_enable_packed_row=true,ysql_beta_features=true,yb_enable_read_committed_isolation=true,enable_deadlock_detection=true,enable_wait_queues=true" --master_flags="ysql_enable_packed_row=true,ysql_beta_features=true" --daemon=false --join=yugabyted-0
#      bin/yugabyted configure data_placement --constraint_value=cloud.region.zone3 --fault_tolerance=zone --rf=3
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7002:7000"
      - "9002:9000"
      - "5435:5433"
    depends_on:
      - yugabyted-0
```

This will start a 3-node cluster, but the 2nd and 3rd node joins the cluster as read replica node as shown in the Tablet-Servers page of Master Webserver UI.
![Screenshot 2023-09-15 at 9 26 56 AM](https://github.com/yugabyte/yugabyte-db/assets/41946894/c6aeb5c0-fd10-4cc4-9f5d-540a0bae66a8)

This happens due to the fact the placement UUID for 2nd and 3rd nodes are not set properly while starting the node sue to which they are not treated as part of primary cluster.

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.
