### ISSUE TITLE
[yugabyted] Alerts page not working when cluster is deployed using docker.

### ISSUE THREAD

**Issue by gargsans-yb** [yugabyte/yugabyte-db#20537]
Jira Link: [DB-9548](https://yugabyte.atlassian.net/browse/DB-9548)
### Description

Docker deployed yugabyte cluster using yugabyted:
```
services:
  yugabyted-0:
    container_name: yugabyted-0
    hostname: yugabyted-0
    image: yugabytedb/yugabyte:2.20.0.0-b76
    platform: linux/amd64
    command:
    - sh
    - -c
    - |
      bin/yugabyted start --fault_tolerance=zone --daemon=false --advertise_address=yugabyted-0 --cloud_location=cloud.region.zone1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "7000:7000"
      - "7100:7100"
      - "9000:9000"
      - "5433:5433"
      - "15433:15433"
    healthcheck:
       test: ["CMD", "/home/yugabyte/postgres/bin/pg_isready", "-h", "yugabyted-0"]
       interval: 10s
       timeout: 5s
       retries: 10
```

The UI comes up fine but the alerts page should show the `ntp/chrony`, `insecure` slerts. It shows the DOT on the `Alerts` row of the side panel but no alerts are shown when the page is opened:

<img width="1721" alt="Screenshot 2024-01-10 at 3 22 45 PM" src="https://github.com/yugabyte/yugabyte-db/assets/41946894/fa1f0b09-7b15-4583-bba2-8fa1baf9512f">

<img width="1725" alt="Screenshot 2024-01-10 at 3 22 52 PM" src="https://github.com/yugabyte/yugabyte-db/assets/41946894/00baf79c-c08e-4ca6-bd6e-20214af3472c">

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-9548]: https://yugabyte.atlassian.net/browse/DB-9548?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
