### ISSUE TITLE
[docs] Update GKE page with YSQL and creation of external load balancer

### ISSUE THREAD

**Issue by ajcaldera1** [yugabyte/yugabyte-db#2071]
On page: https://docs.yugabyte.com/latest/deploy/public-clouds/gcp/#gke

We do not show an example of how to connect to YSQL nor do we show the 5433 port as part of the example. We should also document how to create an external load balancer so that applications out of the kube cluster can access the database inside. 

An example like the following could be used:
```
apiVersion: v1
kind: Service
metadata:
  name: my-pg-service
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: yb-tserver
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5433
  type: LoadBalancer
```
This would be executed by copying and pasting into a file called pg_service.yaml and running: `kubectl apply -f pg_service.yaml`

Also on the terraform page: https://docs.yugabyte.com/latest/deploy/public-clouds/gcp/#terraform -- There is a formatting bug on the 2nd bullet of item 1, where the unformatted text-box begins.
