### ISSUE TITLE
[YSQL] Unable to set password for `yugabtye` user in K8s/Helm installation when using Connection Manager 

### ISSUE THREAD

**Issue by yogendra** [yugabyte/yugabyte-db#21107]
### Description

When deploying YugabyteDB database using Helm, we can provide `authCredentials.ysql.password` value to set the password for `yugabyte` user. But if we use connection manager (setting `gflags.tserver.enable_ysql_conn_mgr=true`), password for `yugabyte` user is not assigned correctly and remains as default password (`yugabyte`)

Step to test
## Installation Behaviour without Connection Manager - Passed

**Result:** Password is set for `yugabyte` user correctly

Steps:

1. Create a `values.yaml` file for helm installation
    
    ```yaml
    # file: values-nocm.yaml
    authCredentials:
      ysql:
        password: "Password#123"
    gflags:
      master: {}
      tserver: {} # no gflags for tserver
    resource:
      master:
        requests:
          cpu: 0.5
          memory: 0.5Gi
        limits:
          cpu: 0.5
          memory: 0.5Gi
      tserver:
        requests:
          cpu: 0.5
          memory: 0.5Gi
        limits:
          cpu: 0.5
          memory: 0.5Gi
    replicas:
      master: 1
      tserver: 1
    enableLoadBalancer: false`
    ```
1. Start a kind cluster

    ```bash
    kind create cluster
    ```

1. Create namesapce

    ```
    kubectl create namespace ybdb
    ```

1. (one time) Add yb helm repo

    ```bash
    helm repo add yugabytedb https://charts.yugabyte.com
    helm repo update
    ```
1. install yb via helm

    ```bash
    helm install  ybdb -n ybdb yugabytedb/yugabyte --version 2.20.1 -f values-nocm.yaml --wait
    ```

    Output

    ```log
    NAME: ybdb
    LAST DEPLOYED: Wed Feb 21 02:56:20 2024
    NAMESPACE: ybdb
    STATUS: deployed
    REVISION: 1
    TEST SUITE: None
    NOTES:
    1. Get YugabyteDB Pods by running this command:
      kubectl --namespace ybdb get pods
    
    3. Get list of YugabyteDB services that are running:
      kubectl --namespace ybdb get services
    
    4. Get information about the load balancer services:
      kubectl get svc --namespace ybdb
    
    5. Connect to one of the tablet server:
      kubectl exec --namespace ybdb -it yb-tserver-0 bash
    
    6. Run YSQL shell from inside of a tablet server:
      kubectl exec --namespace ybdb -it yb-tserver-0 -- /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb
    
    7. Cleanup YugabyteDB Pods
      For helm 2:
      helm delete ybdb --purge
      For helm 3:
      helm delete ybdb -n ybdb
      NOTE: You need to manually delete the persistent volume
      kubectl delete pvc --namespace ybdb -l app=yb-master
      kubectl delete pvc --namespace ybdb -l app=yb-tserver
    ```

1. Try to connect via password
    
    ```bash
    > kubectl exec --namespace ybdb -it yb-tserver-0 -- bash 
    [root@yb-tserver-0 cores]# PGPASSWORD=Password#123  /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb -c 'select version();'
                                                                                                version                                                                                            
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    PostgreSQL 11.2-YB-2.20.1.3-b0 on aarch64-unknown-linux-gnu, compiled by clang version 16.0.6 (https://github.com/yugabyte/llvm-project.git 1e6329f40e5c531c09ade7015278078682293ebd), 64-bit
    (1 row)

    [root@yb-tserver-0 cores]# PGPASSWORD=yugabyte  /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb -c 'select version();'
    ysqlsh: FATAL:  password authentication failed for user "yugabyte"
    ```

## Installation Behaviour with Connection Manager - Failed

**Result:** Password is not set for `yugabyte` user.  And we need to use default password

Steps:

1. Create a `values.yaml` file for helm installation
    
    ```yaml
    # file: values-withcm.yaml
    authCredentials:
      ysql:
        password: "Password#123"
    gflags:
      master: {}
      tserver:
        enable_ysql_conn_mgr: "true"
        allowed_preview_flags_csv: enable_ysql_conn_mgr
    resource:
      master:
        requests:
          cpu: 0.5
          memory: 0.5Gi
        limits:
          cpu: 0.5
          memory: 0.5Gi
      tserver:
        requests:
          cpu: 0.5
          memory: 0.5Gi
        limits:
          cpu: 0.5
          memory: 0.5Gi
    replicas:
      master: 1
      tserver: 1
    enableLoadBalancer: false`
    ```
1. Start a kind cluster

    ```bash
    kind create cluster
    ```

1. Create namesapce

    ```
    kubectl create namespace ybdb
    ```

1. (one time) Add yb helm repo

    ```bash
    helm repo add yugabytedb https://charts.yugabyte.com
    helm repo update
    ```
1. install yb via helm

    ```bash
    helm install  ybdb -n ybdb yugabytedb/yugabyte --version 2.20.1 -f values-withcm.yaml --wait
    ```

    Output

    ```log
    NAME: ybdb
    LAST DEPLOYED: Wed Feb 21 02:56:20 2024
    NAMESPACE: ybdb
    STATUS: deployed
    REVISION: 1
    TEST SUITE: None
    NOTES:
    1. Get YugabyteDB Pods by running this command:
      kubectl --namespace ybdb get pods
    
    3. Get list of YugabyteDB services that are running:
      kubectl --namespace ybdb get services
    
    4. Get information about the load balancer services:
      kubectl get svc --namespace ybdb
    
    5. Connect to one of the tablet server:
      kubectl exec --namespace ybdb -it yb-tserver-0 bash
    
    6. Run YSQL shell from inside of a tablet server:
      kubectl exec --namespace ybdb -it yb-tserver-0 -- /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb
    
    7. Cleanup YugabyteDB Pods
      For helm 2:
      helm delete ybdb --purge
      For helm 3:
      helm delete ybdb -n ybdb
      NOTE: You need to manually delete the persistent volume
      kubectl delete pvc --namespace ybdb -l app=yb-master
      kubectl delete pvc --namespace ybdb -l app=yb-tserver
    ```

1. Try to connect via password
    
    ```bash
    > kubectl exec --namespace ybdb -it yb-tserver-0 -- bash 
    [root@yb-tserver-0 cores]#  PGPASSWORD=Password#123  /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb -c 'select version();'
    ysqlsh: ERROR:  password authentication failed for user "yugabyte"
    [root@yb-tserver-0 cores]#  PGPASSWORD=yugabyte  /home/yugabyte/bin/ysqlsh -h yb-tserver-0.yb-tservers.ybdb -c 'select version();'
                                                                                                version                                                                                            
    -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
     PostgreSQL 11.2-YB-2.20.1.3-b0 on aarch64-unknown-linux-gnu, compiled by clang version 16.0.6 (https://github.com/yugabyte/llvm-project.git 1e6329f40e5c531c09ade7015278078682293ebd), 64-bit
    (1 row) 
    ```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.
