### ISSUE TITLE
[yugabyted] ERROR: A node is already running on

### ISSUE THREAD

**Issue by onyn** [yugabyte/yugabyte-db#21687]
Jira Link: [DB-10571](https://yugabyte.atlassian.net/browse/DB-10571)
### Description

Playing around with yugabytedb. Created 3-node universe with nodes running in docker:
<details>
  <summary>node1.yml</summary>

  ```yaml
  version: '3.7'
  
  services:
    yugabyte:
      image: yugabytedb/yugabyte:2.20.2.0-b145
      network_mode: host
      volumes:
        - /var/yugabyte:/home/yugabyte/yb_data
      command:
        - "bin/yugabyted"
        - "start"
        - "--callhome=false"
        - "--background=false"
        - "--base_dir=/home/yugabyte/yb_data"
        - "--advertise_address=192.168.0.1"
        - "--ysql_enable_auth=true"
        - "--use_cassandra_authentication=true"
        - "--cloud_location=metal.de.rack1"
        - "--tserver_flags=ysql_pg_conf_csv={password_encryption=scram-sha-256}"
        - "--join=192.168.0.2"
  ```
</details>

<details>
  <summary>node2.yml</summary>

  ```yaml
  version: '3.7'
  
  services:
    yugabyte:
      image: yugabytedb/yugabyte:2.20.2.0-b145
      network_mode: host
      volumes:
        - /var/yugabyte:/home/yugabyte/yb_data
      command:
        - "bin/yugabyted"
        - "start"
        - "--callhome=false"
        - "--background=false"
        - "--base_dir=/home/yugabyte/yb_data"
        - "--advertise_address=192.168.0.2"
        - "--ysql_enable_auth=true"
        - "--use_cassandra_authentication=true"
        - "--cloud_location=metal.de.rack1"
        - "--tserver_flags=ysql_pg_conf_csv={password_encryption=scram-sha-256}"
  ```
</details>

<details>
  <summary>node3.yml</summary>

  ```yaml
  version: '3.7'
  
  services:
    yugabyte:
      image: yugabytedb/yugabyte:2.20.2.0-b145
      network_mode: host
      volumes:
        - /var/yugabyte:/home/yugabyte/yb_data
      command:
        - "bin/yugabyted"
        - "start"
        - "--callhome=false"
        - "--background=false"
        - "--base_dir=/home/yugabyte/yb_data"
        - "--advertise_address=192.168.0.3"
        - "--ysql_enable_auth=true"
        - "--use_cassandra_authentication=true"
        - "--cloud_location=metal.de.rack1"
        - "--tserver_flags=ysql_pg_conf_csv={password_encryption=scram-sha-256}"
        - "--join=192.168.0.2"
  ```
</details>
Universe formed successfully. Several days after I noticed new version of yugabyte docker image (2.20.2.1-b3). And tried to upgrade universe to new version. Started from node1 (follower):

<details>
  <summary>node1.yml</summary>

  ```diff
  services:
    yugabyte:
  -   image: yugabytedb/yugabyte:2.20.2.0-b145
  +   image: yugabytedb/yugabyte:2.20.2.1-b3
      network_mode: host
      volumes:
  ```
</details>

After upgrading, node1 failed to start with cryptic message `ERROR: A node is already running on 192.168.0.2, please specify a valid address.`:

<details>
  <summary>full log</summary>

  ```
  [yugabyted start] 2024-03-26 11:39:28,448 INFO:  | 0.0s | Running yugabyted command: 'bin/yugabyted start --callhome=false --background=false --base_dir=/home/yugabyte/yb_data --advertise_address=192.168.0.1 --ysql_enable_auth=true --use_cassandra_authentication=true --cloud_location=metal.de.rack1 --tserver_flags=ysql_pg_conf_csv={password_encryption=scram-sha-256} --join=192.168.0.2'
  [yugabyted start] 2024-03-26 11:39:28,448 INFO:  | 0.0s | cmd = start using config file: /home/yugabyte/yb_data/conf/yugabyted.conf (args.config=None)
  [yugabyted start] 2024-03-26 11:39:28,448 INFO:  | 0.0s | Found directory /home/yugabyte/bin for file openssl_proxy.sh
  [yugabyted start] 2024-03-26 11:39:28,449 INFO:  | 0.0s | Found directory /home/yugabyte/bin for file yb-admin
  [yugabyted start] 2024-03-26 11:39:28,451 INFO:  | 0.0s | Fetching configs from join IP...
  [yugabyted start] 2024-03-26 11:39:28,451 INFO:  | 0.0s | Trying to get masters information from http://192.168.0.2:9000/api/v1/masters (Timeout=60)
  [yugabyted start] 2024-03-26 11:39:28,458 DEBUG:  | 0.0s | Tserver 192.168.0.2 returned the followingmaster leader 192.168.0.2.
  [yugabyted start] 2024-03-26 11:39:28,461 ERROR:  | 0.0s | ERROR: A node is already running on 192.168.0.2, please specify a valid address.
  For more information, check the logs in /home/yugabyte/yb_data/logs
  ```
</details>
<details>
  <summary>curl http://192.168.0.2:9000/api/v1/masters</summary>

  ```json
  {
      "master_server_and_type": [
          {
              "master_server": "192.168.0.1:7100",
              "is_leader": false
          },
          {
              "master_server": "192.168.0.2:7100",
              "is_leader": true
          },
          {
              "master_server": "192.168.0.3:7100",
              "is_leader": false
          }
      ]
  }
  ```
</details>

Rolling back to 2.20.2.0-b145 does not fix problem. Still fails with same error message.

What's wrong with my setup?

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10571]: https://yugabyte.atlassian.net/browse/DB-10571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
