### ISSUE TITLE
[YSQL] CREATE TABLE in tx cannot be undone with ROLLBACK

### ISSUE THREAD

**Issue by TroyKomodo** [yugabyte/yugabyte-db#21966]
Jira Link: [DB-10881](https://yugabyte.atlassian.net/browse/DB-10881)
### Description

maybe related #17698

Transaction blocks allow for tables to be created during the transaction and then rolled back so the table no longer exists.

On postgres:11.2

```
psql (15.6 (Ubuntu 15.6-0ubuntu0.23.10.1), server 11.2 (Debian 11.2-1.pgdg90+1))
Type "help" for help.

postgres=# begin;
BEGIN
postgres=*# CREATE TABLE test (abc INTEGER NOT NULL);
CREATE TABLE
postgres=*# \dt
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | test | table | postgres
(1 row)

postgres=*# rollback;
ROLLBACK
postgres=# \dt
Did not find any relations.
postgres=# 
```

vs Yugabyte 
```
psql (15.6 (Ubuntu 15.6-0ubuntu0.23.10.1), server 11.2-YB-2.21.0.0-b0)
Type "help" for help.

yugabyte=# begin;
BEGIN
yugabyte=*# CREATE TABLE test (abc INTEGER NOT NULL);
CREATE TABLE
yugabyte=*# \dt
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | test | table | yugabyte
(1 row)

yugabyte=*# rollback;
ROLLBACK
yugabyte=# \dt
        List of relations
 Schema | Name | Type  |  Owner   
--------+------+-------+----------
 public | test | table | yugabyte
(1 row)

yugabyte=# 
```

This is very concerning as now i am not sure what operations can actually be rolled back. I think if this is something that cannot be undone due to the nature of how the distributed database works then when attempting to create a table in a transaction block it should outright fail. 

Commands used to spin up a postgres instance.
```
docker run -p 5432:5432 --rm -e POSTGRES_HOST_AUTH_METHOD=trust postgres:11.2
```

Docker compose for yugabyte cluster setup.

```yaml
x-yb-master-common: &yb-master
  image: yugabytedb/yugabyte
  entrypoint: ./bin/yb-master
  ports:
    - "7000-7003:7000"
    - "5433-5436:5433"

x-yb-tserver-common: &yb-tserver
  image: yugabytedb/yugabyte
  entrypoint: ./bin/yb-tserver 
  ports:
    - "9000-9003:9000"
    - "5443-5446:5433"
    - "13000-13003:13000"

services:
  yb-master1: 
    <<: *yb-master
    volumes:
      - yb-master1:/mount/data
    command:
      - --master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:7100
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-master1:7100
  yb-master2:
    <<: *yb-master
    volumes:
      - yb-master2:/mount/data
    command:
      - --master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:7100
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-master2:7100
  yb-master3:
    <<: *yb-master
    volumes:
      - yb-master3:/mount/data
    command:
      - --master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:7100
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-master3:7100

  yb-tserver1:
    <<: *yb-tserver
    volumes:
      - yb-tserver1:/mount/data
    command:
      - --tserver_master_addrs=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:9100
      - --enable_ysql
      - --pgsql_proxy_bind_address=0.0.0.0:5433
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-tserver1:9100
  yb-tserver2:
    <<: *yb-tserver
    volumes:
      - yb-tserver2:/mount/data
    command:
      - --tserver_master_addrs=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:9100
      - --enable_ysql
      - --pgsql_proxy_bind_address=0.0.0.0:5433
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-tserver2:9100
  yb-tserver3:
    <<: *yb-tserver
    volumes:
      - yb-tserver3:/mount/data
    command:
      - --tserver_master_addrs=yb-master1:7100,yb-master2:7100,yb-master3:7100
      - --rpc_bind_addresses=0.0.0.0:9100
      - --enable_ysql
      - --pgsql_proxy_bind_address=0.0.0.0:5433
      - --fs_data_dirs=/mount/data
      - --logtostderr
      - --server_broadcast_addresses=yb-tserver3:9100

volumes:
  yb-master1:
  yb-master2:
  yb-master3:
  yb-tserver1:
  yb-tserver2:
  yb-tserver3:
```

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

[DB-10881]: https://yugabyte.atlassian.net/browse/DB-10881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
