### ISSUE TITLE
Docker stack, master not starting up

### ISSUE THREAD

**Issue by GameBurrow** [yugabyte/yugabyte-db#2358]
I've been trying to get this running based on the examples provided in [Docker Swarem](https://docs.yugabyte.com/latest/deploy/docker/docker-swarm) and [Docker Compose](https://docs.yugabyte.com/latest/deploy/docker/docker-compose/).

This my resulting **docker-compose**
```
version: "3.7"

services:
  yb-master1:
    image: yugabytedb/yugabyte:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2000M
      restart_policy:
        condition: on-failure
    command: [ "/home/yugabyte/bin/yb-master", 
              "--fs_data_dirs=/mnt/data0", 
              "--master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100", 
              "--replication_factor=3"]
    ports:
    - "7000:7000"
    volumes:
      - "pms-yb-master1:/mnt/data0"
    networks:
      - yugabytedb 

  yb-master2:
    image: yugabytedb/yugabyte:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2000M
      restart_policy:
        condition: on-failure
    command: [ "/home/yugabyte/bin/yb-master", 
              "--fs_data_dirs=/mnt/data0", 
              "--master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100", 
              "--replication_factor=3"]
    volumes:
      - "pms-yb-master2:/mnt/data0"
    networks:
      - yugabytedb

  yb-master3:
    image: yugabytedb/yugabyte:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2000M
      restart_policy:
        condition: on-failure
    command: [ "/home/yugabyte/bin/yb-master", 
              "--fs_data_dirs=/mnt/data0", 
              "--master_addresses=yb-master1:7100,yb-master2:7100,yb-master3:7100", 
              "--replication_factor=3"]
    volumes:
      - "pms-yb-master3:/mnt/data0"
    networks:
      - yugabytedb 


  yb-tserver:
    image: yugabytedb/yugabyte:latest
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "1"
          memory: 1000M
      restart_policy:
        condition: on-failure
    command: [ "/home/yugabyte/bin/yb-tserver", 
              "--fs_data_dirs=/mnt/data0",
              "--start_pgsql_proxy", 
              "--tserver_master_addrs=yb-master1:7100,yb-master2:7100,yb-master3:7100"]
    volumes:
      - "pms-yb-tserver:/mnt/data0"
    ports:
    - "9042:9042"
    - "6379:6379"
    - "5433:5433"
    - "9000:9000"
    depends_on:
    - yb-master
    networks:
      - yugabytedb

networks:
  yugabytedb:

volumes:
  pms-yb-master1:
  pms-yb-master2:
  pms-yb-master3:
  pms-yb-tserver:
```

After running docker stack using:
```
docker stack deploy --resolve-image never -c docker-compose/db.docker-compose.yml pms-yugabyte
```

tsserver's start up, but none of the masters do.
```
kerts93@Sepaurg-Y740:/d/Muud Kaustad/Töö asjad/Arego/project-management-system$ docker service ls
ID                  NAME                      MODE                REPLICAS            IMAGE                        PORTS
8css0s9xa0em        pms-yugabyte_yb-master1   replicated          0/1                 yugabytedb/yugabyte:latest   *:7000->7000/tcp
sj8pusbpa99l        pms-yugabyte_yb-master2   replicated          0/1                 yugabytedb/yugabyte:latest
wg0g3s9lngzx        pms-yugabyte_yb-master3   replicated          0/1                 yugabytedb/yugabyte:latest
51yzd844r31o        pms-yugabyte_yb-tserver   replicated          4/4                 yugabytedb/yugabyte:latest   *:5433->5433/tcp, *:6379->6379/tcp, *:9000->9000/tcp, *:9042->9042/tcp
```

`docker service ps <master service name>` shows me that all masters throw error:
"task: non-zero exit (1)"

docker service logs doesn't catch anything at all. When I try to mount one of the master's volume on my own computer's drive, I can catch logs:
[logs.zip](https://github.com/yugabyte/yugabyte-db/files/3626116/logs.zip)

**Comment by rkarthik007** [comment]
@ramkumarvs @Arnav15 - could one of you folks please take a look?

**Comment by iSignal** [comment]
Hello @GameBurrow , thanks for trying out yugabytedb with Docker Stack. I am going to try and dig into the issue in more detail but to give you more context in the meantime - the yb-master is complaining that it cannot create the filesystem under /mnt/data0.

> 
E0918 11:20:37.550727     1 main_util.cc:22] IO error (yb/util/env_posix.cc:1024): Could not create new FS layout: Unable to write instance metadata: Failed to SyncDir() parent of /mnt/data0/yb-data/master/instance: /mnt/data0/yb-data/master

**Comment by PhilPhonic** [comment]
Same problem here. I followed the instructions at https://docs.yugabyte.com/latest/deploy/docker/docker-swarm/
The creation of the first two masters works fine. As soon as master3 starts up, all 3 masters start crashing.

**Comment by vrachels** [comment]
got this too while trying to test a different issue.looks like an issue windows

**Comment by jason-kurzik** [comment]
Got same symptoms as other posters today.  Here is my yml file, fully written before finding this issue.  Running latest docker on openSUSE Tumbleweed, no windows involved at all.  The tservers run fine, but the masters do not, crashing as described above.  Yuga deploys successfully on same swarm when using the service commands instead of deploying a stack.


```yml
version: '3.7'

networks:
  yugabytedb:
    driver: overlay

volumes:
  yb-primary-01:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/storage/yuga
  yb-primary-02:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/storage/yuga
  yb-primary-03:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/storage/yuga
  yb-tserver:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/storage/yuga/tserver

services:
  yb-primary-01:
    image: yugabytedb/yugabyte:latest
    networks:
      - yugabytedb
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.yb-primary == true'
          - 'node.labels.yb-node == 01'
    volumes:
      - yb-primary-01:/mnt/master
    ports:
      - "7000:7000"
    environment:
      SERVICE_7000_NAME: tb-master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-primary-01:7100,yb-primary-02:7100,yb-primary-03:7100",
               "--rpc_bind_addresses=yb-primary-01:7100",
               "--replication_factor=3"]
  yb-primary-02:
    image: yugabytedb/yugabyte:latest
    networks:
      - yugabytedb
    deploy:
      placement:
        constraints:
          - 'node.labels.yb-primary==True'
          - 'node.labels.yb-node==02'
    volumes:
      - yb-primary-02:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-primary-01:7100,yb-primary-02:7100,yb-primary-03:7100",
               "--rpc_bind_addresses=yb-primary-02:7100",
               "--replication_factor=3"]
  yb-primary-03:
    image: yugabytedb/yugabyte:latest
    networks:
      - yugabytedb
    deploy:
      placement:
        constraints:
          - 'node.labels.yb-primary==True'
          - 'node.labels.yb-node==03'
    volumes:
      - yb-primary-03:/mnt/master
    command: [ "/home/yugabyte/bin/yb-master",
               "--fs_data_dirs=/mnt/master",
               "--master_addresses=yb-primary-01:7100,yb-primary-02:7100,yb-primary-03:7100",
               "--rpc_bind_addresses=yb-primary-03:7100",
               "--replication_factor=3"]

  yb-tserver:
    image: yugabytedb/yugabyte:latest
    networks:
      - yugabytedb
    deploy:
      mode: global
    volumes:
      - yb-tserver:/mnt/tserver
    ports:
      - "9000:9000"
      - "5443:5443"
      - "9042:9042"
    command: [ "/home/yugabyte/bin/yb-tserver",
               "--fs_data_dirs=/mnt/tserver",
               "--start_pgsql_proxy",
               "--rpc_bind_addresses=0.0.0.0:9100",
               "--tserver_master_addrs=yb-primary-01:7100,yb-primary-02:7100,yb-primary-03:7100"]
    environment:
      SERVICE_5433_NAME: ysql
      SERVICE_9042_NAME: ycql
      SERVICE_9000_NAME: yb-tserver
```
