### ISSUE TITLE
DNS Caching Issue with the tserver

### ISSUE THREAD

**Issue by dmosruby** [yugabyte/yugabyte-db#2390]
Each tserver initially resolves the IP/endpoints of the yb-master service. When each master pod is then restarted, the tserver continues to use the old IP address for the master pods, but because kubernetes reassigns a new IP address on pod restart, this IP is no longer valid. After restarting all three master pods, the tserver no longer is able to connect to any of the masters and continues to log failed to heartbeat and the master admin ui shows no tservers connected. 

The workaround is to restart all tserver pods to retrieve the new pod endpoint/IPs for the master pods.

Initial Endpoints of yb-master
```
[root@host1 ~]# kubectl describe endpoints yb-master -n {namespace}
Name:         yb-master-ui
Namespace:    {namespace}
Labels:       app=yb-master
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.117,10.233.70.172,10.233.76.186
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    ui    7000  TCP
    rpc   7100  TCP
Events:  <none>
Name:         yb-masters
Namespace:    {namespace}
Labels:       app=yb-master
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.117,10.233.70.172,10.233.76.186
  NotReadyAddresses:  <none>
  Ports:
    Name      Port  Protocol
    ----      ----  --------
    rpc-port  7100  TCP
    ui        7000  TCP
Events:  <none>
```
Initial endpoints of yb-tserver
```
[root@host1 ~]# kubectl describe endpoints yb-tservers -n {namespace}
Name:         yb-tservers
Namespace:    {namespace}
Labels:       app=yb-tserver
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.118,10.233.70.173,10.233.76.187
  NotReadyAddresses:  <none>
  Ports:
    Name       Port  Protocol
    ----       ----  --------
    postgres   5433  TCP
    cassandra  9042  TCP
    rpc-port   9100  TCP
    redis      6379  TCP
    ui         9000  TCP
Events:  <none>
```

Delete Pods Cmds
```
[root@host1 ~]# kubectl delete po -n {namespace} yb-master-0
pod "yb-master-0" deleted
[root@host1 ~]# kubectl delete po -n {namespace} yb-master-1
pod "yb-master-1" deleted
[root@host1 ~]# kubectl delete po -n {namespace} yb-master-2
pod "yb-master-2" deleted
```

Resulting endpoints of yb-master
```
[root@host1 ~]# kubectl describe endpoints yb-master -n {namespace}
Name:         yb-master-ui
Namespace:    {namespace}
Labels:       app=yb-master
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.119,10.233.70.174,10.233.76.188
  NotReadyAddresses:  <none>
  Ports:
    Name  Port  Protocol
    ----  ----  --------
    ui    7000  TCP
    rpc   7100  TCP
Events:  <none>
Name:         yb-masters
Namespace:    {namespace}
Labels:       app=yb-master
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.119,10.233.70.174,10.233.76.188
  NotReadyAddresses:  <none>
  Ports:
    Name      Port  Protocol
    ----      ----  --------
    rpc-port  7100  TCP
    ui        7000  TCP
Events:  <none>
```

Resulting endpoints of yb-tserver
```
[root@host1 ~]# kubectl describe endpoints yb-tservers -n {namespace}
Name:         yb-tservers
Namespace:    {namespace}
Labels:       app=yb-tserver
              group={group}
Annotations:  <none>
Subsets:
  Addresses:          10.233.108.118,10.233.70.173,10.233.76.187
  NotReadyAddresses:  <none>
  Ports:
    Name       Port  Protocol
    ----       ----  --------
    postgres   5433  TCP
    cassandra  9042  TCP
    rpc-port   9100  TCP
    redis      6379  TCP
    ui         9000  TCP
Events:  <none>
```

Logs of tserver
```
I0921 00:44:34.241988    47 heartbeater.cc:283] P 90611780d226425293a5fdcd553730cb: Find leader master 10.233.70.172:7100 hit error Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.76.186:7100 timed out after 2.500s
W0921 00:44:34.242048    47 heartbeater.cc:584] P 90611780d226425293a5fdcd553730cb: Failed to heartbeat to 10.233.70.172:7100: Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.76.186:7100 timed out after 2.500s tries=144, num=3, masters=0x00000000030cdf00 -> [[10.233.108.117:7100], [10.233.76.186:7100], [10.233.70.172:7100]], code=Timed out
I0921 00:44:37.742709    47 heartbeater.cc:283] P 90611780d226425293a5fdcd553730cb: Find leader master 10.233.70.172:7100 hit error Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.70.172:7100 timed out after 2.500s
W0921 00:44:37.742782    47 heartbeater.cc:584] P 90611780d226425293a5fdcd553730cb: Failed to heartbeat to 10.233.70.172:7100: Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.70.172:7100 timed out after 2.500s tries=145, num=3, masters=0x00000000030cdf00 -> [[10.233.108.117:7100], [10.233.76.186:7100], [10.233.70.172:7100]], code=Timed out
I0921 00:44:41.244102    47 heartbeater.cc:283] P 90611780d226425293a5fdcd553730cb: Find leader master 10.233.70.172:7100 hit error Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.108.117:7100 timed out after 2.500s
W0921 00:44:41.244148    47 heartbeater.cc:584] P 90611780d226425293a5fdcd553730cb: Failed to heartbeat to 10.233.70.172:7100: Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.108.117:7100 timed out after 2.500s tries=146, num=3, masters=0x00000000030cdf00 -> [[10.233.108.117:7100], [10.233.76.186:7100], [10.233.70.172:7100]], code=Timed out
I0921 00:44:44.745252    47 heartbeater.cc:283] P 90611780d226425293a5fdcd553730cb: Find leader master 10.233.70.172:7100 hit error Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.70.172:7100 timed out after 2.500s
W0921 00:44:44.745292    47 heartbeater.cc:584] P 90611780d226425293a5fdcd553730cb: Failed to heartbeat to 10.233.70.172:7100: Timed out (yb/rpc/outbound_call.cc:510): GetMasterRegistration RPC to 10.233.70.172:7100 timed out after 2.500s tries=147, num=3, masters=0x00000000030cdf00 -> [[10.233.108.117:7100], [10.233.76.186:7100], [10.233.70.172:7100]], code=Timed out
```

**Comment by kmuthukk** [comment]
@Arnav15 -- assigning to you for an initial look. If you think it is a server-side issue, we can reassign as appropriate.

CC: @rkarthik007 , @spolitov

**Comment by rkarthik007** [comment]
@Arnav15 - any progress on this? I am curious because we do rolling upgrades - wondering if we experience a large unavailability in k8s.

**Comment by Arnav15** [comment]
@dmosruby Could you please tell us a little more about your deployment? We tried to repro this issue by rolling our masters and then checking if the tservers could still talk to the cluster after and the cluster was still in a working state.

**Comment by dmosruby** [comment]
This was seen using the yugabytedb/yugabyte:2.0.0.0-b16 docker image as a 3 node cluster.
For our deployment, we replace the Kubernetes Loadbalancer with NodePort because we deploy our services on-premise and we don't have a cloud provider's external loadbalancer.
This was the kubernetes yaml that we deployed:
```
# 
# Overall Design:
#   There are two Kubernetes StatefulSets in this yaml file - yb-master and yb-tserver. Each of
#   these has the following:
#    - a headless service to expose a DNS entry for discovery
#    - a service to expose end-points to the outside world
#    - the stateful set itself
#    - a load-balancer service to view the universe dashboard UI
#
# Using YB with k8s
#    - Create cluster    : kubectl apply -f yugabyte-statefulset.yaml
#    - List the pods     : kubectl get pods
#    - Run cqlsh         : kubectl exec -it yb-tserver-0 /home/yugabyte/bin/cqlsh
#    - Run Redis cli     : kubectl exec -it yb-tserver-0 /home/yugabyte/bin/redis-cli
#    - Run psql          : kubectl exec -it yb-tserver-0 /home/yugabyte/postgres/bin/psql --
#                             -U postgres -d postgres -h yb-tserver-0 -p 5433
#    - Connect to the ui : kubectl port-forward yb-master-0 7000
#                          You can now view the UI at http://localhost:7000
#    - Destroy cluster   : kubectl delete -f yugabyte-statefulset.yaml

apiVersion: v1
kind: Service
metadata:
  # This is a "headless" service for the yb-master which exists to allow discovery of the set of
  # member pods (masters). The CNAME of this service points to SRV records - one for each Pod that
  # is Running and Ready). Read more in the Kubernetes docs:
  # https://kubernetes.io/docs/tutorials/stateful-application/basic-stateful-set/
  name: yb-masters
  labels:
    app: yb-master
spec:
  clusterIP: None
  ports:
  - name: ui
    port: 7000
  - name: rpc-port
    port: 7100
  selector:
    app: yb-master
---
apiVersion: v1
kind: Service
metadata:
  name: yb-master-ui
  labels:
    app: yb-master
spec:
  ports:
  - name: ui
    port: 7000
    nodePort: 32070
  - name: rpc
    port: 7100
    nodePort: 32071
  selector:
    app: yb-master
  type: NodePort
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yb-master
  labels:
    app: yb-master
spec:
  serviceName: yb-masters
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: yb-master
  template:
    metadata:
      labels:
        app: yb-master
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - yb-master
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: yb-master
        image: yugabytedb/yugabyte:2.0.0.0-b16
        imagePullPolicy: IfNotPresent
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
          - "/home/yugabyte/bin/yb-master"
          - "--fs_data_dirs=/mnt/data0"
          - "--rpc_bind_addresses=$(POD_IP):7100"
          - "--server_broadcast_addresses=$(POD_NAME).yb-masters.default.svc.cluster.local:7100"
          - "--use_private_ip=never"
          - "--master_addresses=yb-masters.default.svc.cluster.local:7100"
          # To disable YugaByte SQL API functionality, comment the
          # "use_initial_sys_catalog_snapshot" flag below.
          # Flag support added after version 1.3.
          - "--use_initial_sys_catalog_snapshot=true"
          - "--master_replication_factor=3"
          - "--replication_factor=3"
          - "--logtostderr"
          - "--callhome_enabled=false"
        ports:
        - containerPort: 7000
          name: master-ui
        - containerPort: 7100
          name: master-rpc
#        readinessProbe:
#          tcpSocket:
#            port: 7100
#          initialDelaySeconds: 5
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: 7100
#          initialDelaySeconds: 15
#          periodSeconds: 10
        resources:
          limits:
            cpu: "8"
            memory: 32Gi
          requests:
            cpu: 2m
            memory: 2Gi
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: datadir
          mountPath: /mnt/data0
  updateStrategy:
    type: RollingUpdate
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      storageClassName: hspc
---
apiVersion: v1
kind: Service
metadata:
  # This is a "headless" service for the yb-tserver which exists to allow discovery of the set of
  # member pods (tservers).
  name: yb-tservers
  labels:
    app: yb-tserver
spec:
  clusterIP: None
  ports:
  - name: ui
    port: 9000
  - name: rpc-port
    port: 9100
  - name: cassandra
    port: 9042
  - name: redis
    port: 6379
  - name: postgres
    port: 5433
  selector:
    app: yb-tserver
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: yb-tserver
  labels:
    app: yb-tserver
spec:
  serviceName: yb-tservers
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: yb-tserver
  template:
    metadata:
      labels:
        app: yb-tserver
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - yb-tserver
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: yb-tserver
        image: yugabytedb/yugabyte:2.0.0.0-b16
        imagePullPolicy: IfNotPresent
        env:
          - name: GET_HOSTS_FROM
            value: dns
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        command:
          - "/home/yugabyte/bin/yb-tserver"
          - "--fs_data_dirs=/mnt/data0"
          - "--rpc_bind_addresses=$(POD_IP):9100"
          - "--server_broadcast_addresses=$(POD_NAME).yb-tservers:9100"
          # To disable YugaByte SQL API functionality, comment the below two pgsql_xx flags.
          - "--start_pgsql_proxy"
          - "--pgsql_proxy_bind_address=$(POD_IP):5433"
          - "--use_private_ip=never"
          - "--tserver_master_addrs=yb-masters.default.svc.cluster.local:7100"
          - "--tserver_master_replication_factor=3"
          - "--logtostderr"
          - "--callhome_enabled=false"
        ports:
        - containerPort: 9000
          name: tserver-ui
        - containerPort: 9100
          name: tserver-rpc
        - containerPort: 9042
          name: cassandra
        - containerPort: 6379
          name: redis
        - containerPort: 5433
          name: postgres
        resources:
          limits:
            cpu: "8"
            memory: 32Gi
          requests:
            cpu: 2m
            memory: 2Gi
        # These volume mounts are persistent. They are like inline claims,
        # but not exactly because the names need to match exactly one of
        # the stateful pod volumes.
        volumeMounts:
        - name: datadir
          mountPath: /mnt/data0
  updateStrategy:
    type: RollingUpdate
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Gi
      storageClassName: hspc
---
apiVersion: v1
kind: Service
metadata:
  name: yb-tserver-proxy
  labels:
    app: yb-tserver
spec:
  ports:
  - port: 9000
    name: tserver-ui
    nodePort: 31900
  - port: 9100
    name: tserver-rpc
    nodePort: 31910
  - port: 9042
    name: cassandra
    nodePort: 31942
  - port: 6379
    name: redis
    nodePort: 31637
  - port: 5433
    name: postgres
    nodePort: 31543
  selector:
    app: yb-tserver
  type: NodePort
```
