### ISSUE TITLE
[YSQL] Runtime error: load of misaligned address(UndefinedBehaviorSanitizer: undefined-behavior code/crc32c_sse4.cc:235:7) 

### ISSUE THREAD

**Issue by ycybfhb** [yugabyte/yugabyte-db#24188]
### Version:
```
PostgreSQL 11.2-YB-2.25.0.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 17.0.6 (https://github.com/yugabyte/llvm-project.git 9b881774e40024e901fc6f3d313607b071c08631), 64-bit
```
### Docker Error Log
```
code/crc32c_sse4.cc:235:7: runtime error: load of misaligned address 0x51a00003287c for type 'const size_t' (aka 'const unsigned long'), which requires 8 byte alignment
0x51a00003287c: note: pointer points here
  52 5f 54 59 50 45 10 e7  07 12 0d 0a 09 50 52 45  5f 56 4f 54 45 52 10 00  12 09 0a 05 56 4f 54 45
              ^ 
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior code/crc32c_sse4.cc:235:7 in  
```
## Error Message
The issue originates from line 235 in [`crc32c_sse4.cc`](https://github.com/yugabyte/crcutil/blob/master/code/crc32c_sse4.cc), where the macro `CRC_UPDATE_WORD_4` attempts to load the `src` pointer as a `size_t` type. However, the alignment of `src` may not meet the alignment requirements for `size_t`, which can result in undefined behavior. This issue could potentially be resolved by adjusting the code to ensure proper alignment before the load operation. The following modification may address this:

```diff
diff --git a/crc32c_sse4.cc b/crc32c_sse4.cc
index 5194c6e..e23d563 100644
--- a/crc32c_sse4.cc
+++ b/crc32c_sse4.cc
@@ -188,8 +188,8 @@ size_t Crc32cSSE4::Crc32c(const void *data, size_t bytes, Crc crc0) const {
   //    generic table-based CRC computation.
   //
   // In case of X5550 CPU, break even point is at 2KB -- exactly.
-  if (bytes >= 2 * 1024) {
-    while ((reinterpret_cast<size_t>(src) & (sizeof(Word) - 1)) != 0) {
+
+    while ((reinterpret_cast<size_t>(src) & (sizeof(size_t) - 1)) != 0) {
       if (src >= end) {
         return (crc0 ^ Base().Canonize());
       }
@@ -197,7 +197,7 @@ size_t Crc32cSSE4::Crc32c(const void *data, size_t bytes, Crc crc0) const {
       src += 1;
     }
     bytes = static_cast<size_t>(end - src);
-  }
+
   if (src >= end) {
     return (crc0 ^ Base().Canonize());
   }
```
#### Build
The build is performed in the AlmaLinux 8 environment, and name the compressed file as `yb.tar.gz`.
```bash
git clone git@github.com:yugabyte/yugabyte-db.git
cd yugabyte-db
./yb_build.sh asan
./yb_release --skip_build --build_archive --build_root /home/yugabyte-db/build/asan-clang17-dynamic --no_odyssey --no_yugabyted_ui
```
#### Create Docker Image and Container
```bash
docker build -t my_yugabyte:latest .
export YB_SUBNET=10.1.3
docker compose up -d
```
Dockerfile
```
FROM yugabytedb/yugabyte:latest

RUN rm -rf /home/yugabyte/*
COPY ./yb.tar.gz /tmp
RUN tar xf /tmp/yb.tar.gz -C /home/yugabyte --strip-components 1
```
docker-compose.yaml
```
x-service-defaults: &service_defaults
  image: my_yugabyte:latest
  tmpfs:
    - /tmp
  environment:
    SERVICE_5433_NAME: ysql
    SERVICE_9042_NAME: ycql
    SERVICE_6379_NAME: yedis
    SERVICE_7000_NAME: yb-master
    SERVICE_9000_NAME: yb-tserver
    ASAN_OPTIONS: detect_leaks=0:use_sigaltstack=false

services:
  master:
    <<: *service_defaults
    volumes:
      - master-data-1:/mnt/master
    command:
      - "/home/yugabyte/bin/yb-master"
      - "--fs_data_dirs=/mnt/master"
      - "--master_addresses=master:7100"
      - "--rpc_bind_addresses=master:7100"
      - "--replication_factor=1"
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.11

  tserver1:
    <<: *service_defaults
    volumes:
      - tserver-data-1:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver1:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.21

  tserver2:
    <<: *service_defaults
    volumes:
      - tserver-data-2:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver2:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.22

  tserver3:
    <<: *service_defaults
    volumes:
      - tserver-data-3:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver3:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.23

networks:
  yb-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${YB_SUBNET:?please provide subnet range like `10.3.1`}.0/24
          gateway: ${YB_SUBNET}.1

volumes:
  master-data-1:
  tserver-data-1:
  tserver-data-2:
  tserver-data-3:
```
### About Us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in Yugabyte that may lead to database crashes.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.
