### ISSUE TITLE
[YSQL] `FailedAssertion("!(!bms_is_empty(unbatchablerelids) || bms_equal(pclause_batched_inner_attnos, batched_inner_attnos))"`, and server closed the connection unexpectedly.

### ISSUE THREAD

**Issue by ycybfhb** [yugabyte/yugabyte-db#24187]
### Version:
```
PostgreSQL 11.2-YB-2.25.0.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 17.0.6 (https://github.com/yugabyte/llvm-project.git 9b881774e40024e901fc6f3d313607b071c08631), 64-bit
```
### Error Message:
```
TRAP: FailedAssertion("!(!bms_is_empty(unbatchablerelids) || bms_equal(pclause_batched_inner_attnos, batched_inner_attnos))", File: "../../../../../../../src/postgres/src/backend/optimizer/path/indxpath.c", Line: 783)
2024-09-29 04:59:34.949 UTC [71] WARNING:  server process (PID 62614) was terminated by signal 6: Aborted
```
#### Build
The build is performed in the AlmaLinux 8 environment, and name the compressed file as `yb.tar.gz`.
```bash
git clone git@github.com:yugabyte/yugabyte-db.git
cd yugabyte-db
./yb_build.sh asan
./yb_release --skip_build --build_archive --build_root /home/yugabyte-db/build/asan-clang17-dynamic --no_odyssey --no_yugabyted_ui
```
#### Create Docker Image and Container
```bash
docker build -t my_yugabyte:latest .
export YB_SUBNET=10.1.3
docker compose up -d
```
Dockerfile
```
FROM yugabytedb/yugabyte:latest

RUN rm -rf /home/yugabyte/*
COPY ./yb.tar.gz /tmp
RUN tar xf /tmp/yb.tar.gz -C /home/yugabyte --strip-components 1
```
docker-compose.yaml
```
x-service-defaults: &service_defaults
  image: my_yugabyte:latest
  tmpfs:
    - /tmp
  environment:
    SERVICE_5433_NAME: ysql
    SERVICE_9042_NAME: ycql
    SERVICE_6379_NAME: yedis
    SERVICE_7000_NAME: yb-master
    SERVICE_9000_NAME: yb-tserver
    ASAN_OPTIONS: detect_leaks=0:use_sigaltstack=false

services:
  master:
    <<: *service_defaults
    volumes:
      - master-data-1:/mnt/master
    command:
      - "/home/yugabyte/bin/yb-master"
      - "--fs_data_dirs=/mnt/master"
      - "--master_addresses=master:7100"
      - "--rpc_bind_addresses=master:7100"
      - "--replication_factor=1"
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.11

  tserver1:
    <<: *service_defaults
    volumes:
      - tserver-data-1:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver1:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.21

  tserver2:
    <<: *service_defaults
    volumes:
      - tserver-data-2:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver2:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.22

  tserver3:
    <<: *service_defaults
    volumes:
      - tserver-data-3:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver3:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.23

networks:
  yb-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${YB_SUBNET:?please provide subnet range like `10.3.1`}.0/24
          gateway: ${YB_SUBNET}.1

volumes:
  master-data-1:
  tserver-data-1:
  tserver-data-2:
  tserver-data-3:
```

## Reproduce
Firstly, connect to the database via the `psql` command. 

Secondly, execute the statements in `init.sql` to create the tables.

Finally, when executing the following statements, a crash occurred, and the server closed the connection.
```sql
select  
    cast((cast(cast(null as "time") as "time") - cast(cast(null as "interval") as "interval")) as "time") as c_s8mz_2917, 
    ref_0.c_v85ohw8yd as c_k4_2918, 
    pg_catalog.jsonb_delete(
      cast(cast(null as jsonb) as jsonb), 
      cast(pg_catalog.lpad(
        cast(case when (cast((cast(cast(null as circle) as circle) >= cast(cast(null as circle) as circle)) as bool)) then ref_0.c_gfvd6rqp else (select c_y5m2sv_ from t_buksrm7ac3 order by c_y5m2sv_ limit 1 offset 2)
             end
           as text), 
        cast((abs(1281403065%4294967296)-2147483648) as int4), 
        cast(ref_0.c_j36 as text)) as text)) as c_b9aivs_2919, 
    ref_0.c_cr_hoi as c_tem35tdczz_2920, 
    cast((abs(coalesce(
      2005426017, 
      1122787506
      )%4294967296)-2147483648) as int4) as c__q_2921, 
    ref_0.c_xrgtmyt as c_jz1gubpxk_2922, 
    ref_0.c_d0 as c_dz_2923, 
    ref_0.c_v85ohw8yd as c_qgjh_2924, 
    cast((cast(cast(null as numrange) as numrange) &> cast(cast(null as numrange) as numrange)) as bool) as c_h61k_2925, 
    case when (cast((cast(ref_0.c_gfvd6rqp as text) <> cast(ref_0.c_j36 as text)) as bool)) then ref_0.c_d0 else 'znwm' end
       as c_vheh_2926, 
    ref_0.c_gfvd6rqp as c_us8__2927, 
    ref_0.c_x7 as c_lwi1ca7hkq_2928
  from 
    t_k1 as ref_0
  where (EXISTS (
    select  
        ref_1.c_hdp_rp_e as c_r1_2910, 
        case when (cast((cast(cast(null as "time") as "time") >= cast(cast(null as "time") as "time")) as bool)) then (select c_hdp_rp_e from t_buksrm7ac3 order by c_hdp_rp_e limit 1 offset 5)
             else (ref_1.c__c9houo between -949690815 and (select c_i from v_bj9vgampt order by c_i limit 1 offset 5)
              ) end
           as c_y9jz5z_2911, 
        ref_1.c_jdb as c_tc8hnj4vaz_2912, 
        pg_catalog.circle_below(
          cast(cast(null as circle) as circle), 
          cast(cast(null as circle) as circle)) as c_eu0belb2n_2913, 
        pg_catalog.getpgusername() as c_wnurt9t_2914, 
        ref_0.c_j36 as c_ff6s_2915, 
        ref_1.c_oofi as c_tob8p_2916
      from 
        t_buksrm7ac3 as ref_1
      where (cast((cast(cast(null as box) as box) && cast(cast(null as box) as box)) as bool))))
union
(
select  
    cast(null as "time") as c_og3, 
    (cast((cast(null as "numeric") > cast(null as "numeric")) as bool)) as c_t7_2943, 
    cast(null as jsonb) as c_x1zrc, 
    ref_5.c_qrtbufnfx as c_qz_216_vr, 
    cast((abs((cast((abs(ref_9.c_aoschc%4294967296)-2147483648) as int4) # cast((abs(ref_4.c__c9houo%4294967296)-2147483648) as int4))%4294967296)-2147483648) as int4) as c_zoi31kz1, 
    ((select c_aeoo from t_buksrm7ac3 order by c_aeoo limit 1 offset 6)
         not in (
      ref_3.c_n6, ref_6.c_n6)) as c_s_2944, 
    'j' as c_id5waiqm94, 
    (subq_0.c_l3hvzfqit_2939 between ref_6.c_nhx48_sftf and ref_6.c_i) as c_jc_eh, 
    (ref_3.c_kfwk6pdk >= ( 
      select  
            (cast((cast(cast(null as polygon) as polygon) &< cast(cast(null as polygon) as polygon)) as bool)) as c_nlxknu4ox
          from 
            t_k1 as ref_16
          where (cast((cast(-257.1 as float8) <> cast(35.62 as float8)) as bool))
        union
        (
        select  
            (subq_0.c_px_2940 not in (
              select  
                  ref_18.c_oofi as c_hlnc_g1bqo
                from 
                  t_buksrm7ac3 as ref_18
                where (cast((cast(cast(null as tsquery) as tsquery) > cast(cast(null as tsquery) as tsquery)) as bool)))) as c_r10gcwsp4
          from 
            t_h7jxln5tx3 as ref_17
          where ((ref_17.c_q2t not like '%5g5pkt0p1')) 
            and ((cast((cast(cast(null as box) as box) <^ cast(cast(null as box) as box)) as bool)))
        )
         limit 1)) as c_fb_2945, 
    ref_3.c_g_ius6q as c_u_zaxryhz8, 
    (select c_q2t from t_h7jxln5tx3 order by c_q2t limit 1 offset 3)
       as c_hfh, 
    ref_5.c_qrtbufnfx as c_v15mqvw
  from 
    ((select  
            pg_catalog.max(
            cast(ref_2.c_y5m2sv_ as text)) as c_dqp84e_2929, 
            pg_catalog.min(
            cast((abs(ref_2.c_bgg551bp%4294967296)-2147483648) as int4)) as c_nx_2930, 
            ref_2.c_k as c_igx5_70d_2931, 
            pg_catalog.string_agg(
            cast(ref_2.c_y5m2sv_ as text), 
            cast(ref_2.c_jdb as text)) as c_nqkxbd_2932, 
            pg_catalog.string_agg(
            cast(ref_2.c_qrtbufnfx as text), 
            cast(ref_2.c_jdb as text)) as c_g_2933, 
            pg_catalog.bool_and(
            cast((cast((cast(null as inet) > cast(null as inet)) as bool)) as bool)) as c_rio8_2934, 
            pg_catalog.sum(
            cast(ref_2.c_k as float4)) as c_z724_2935, 
            pg_catalog.bool_or(
            cast((cast((cast(ref_2.c_aeoo as int8) <= cast(ref_2.c_aeoo as int8)) as bool)) as bool)) as c_l2mf2_n6x_2936, 
            pg_catalog.min(
            cast(ref_2.c_jdb as text)) as c_ctgmxwcm_2937, 
            pg_catalog.max(
            cast(ref_2.c_jdb as text)) as c__z_2938, 
            pg_catalog.min(
            cast((abs(ref_2.c__c9houo%4294967296)-2147483648) as int4)) as c_l3hvzfqit_2939, 
            pg_catalog.sum(
            cast(ref_2.c_oofi as float4)) as c_px_2940
          from 
            t_buksrm7ac3 as ref_2
          where (false) 
            or ((ref_2.c__c9houo between ref_2.c__c9houo and ref_2.c_aeoo))
          group by ref_2.c_k) as subq_0
      right outer join (v_bj9vgampt as ref_3
        left outer join (((t_buksrm7ac3 as ref_4
              left outer join t_buksrm7ac3 as ref_5
              on ((cast((ref_5.c_bgg551bp = ref_5.c__c9houo) as bool))))
            left outer join v_bj9vgampt as ref_6
            on ((EXISTS (
                select  
                    ref_7.c_gfvd6rqp as c_ai_r37v54__2941
                  from 
                    t_k1 as ref_7
                  where (ref_4.c_hdp_rp_e is NULL)
                  limit 111))))
          left outer join (t_k1 as ref_8
            left outer join t_h7jxln5tx3 as ref_9
            on ((ref_9.c_xqci4k5e1y between (select pg_catalog.bit_or(c_aoschc) from t_h7jxln5tx3)
                   and ref_9.c_aoschc)))
          on (ref_5.c__c9houo = ref_9.c_aoschc ))
        on ((cast((cast(cast(null as xid) as xid) <> cast(cast(null as xid) as xid)) as bool))))
      on ((ref_3.c_t2ertqb1i between (select pg_catalog.bit_or(c__c9houo) from t_buksrm7ac3)
             and ref_4.c_bgg551bp)))
  where (EXISTS (
    select  
        ref_5.c_qrtbufnfx as c_hph_nwm75y, 
        subq_0.c_g_2933 as c_eiwsb, 
        ref_10.c_d0 as c_yy7k6q, 
        ref_9.c_ycwjffoeiy as c_i_ifea, 
        ref_10.c_v85ohw8yd as c_gdn_piyc3, 
        case when (((select c_q2t from t_h7jxln5tx3 order by c_q2t limit 1 offset 3)
                 not like 'h1b%aq')) 
            or ((cast((ref_4.c_bgg551bp = ref_4.c_aeoo) as bool))) then ref_3.c_nhx48_sftf else ref_5.c_bgg551bp end
           as c_x9el, 
        case when (EXISTS (
            select  
                cast((abs((select pg_catalog.var_samp(c_i) from v_bj9vgampt)
                  %65536)-32768) as int2) as c_rs2gwv6, 
                ref_10.c_x7 as c_efi7, 
                ref_15.c_nhx48_sftf as c_w_2942
              from 
                v_bj9vgampt as ref_15
              where (ref_8.c_rjo90 is not NULL))) then ref_3.c_t2ertqb1i else ref_5.c_aeoo end
           as c_jnfeo
      from 
        t_k1 as ref_10
      where (ref_8.c_rjo90 in (
        select  
              ref_11.c_gfvd6rqp as c_ng90n2qxh
            from 
              ((t_k1 as ref_11
                  cross join t_buksrm7ac3 as ref_12
                  )
                left outer join t_buksrm7ac3 as ref_13
                on ((ref_11.c_gfvd6rqp like '_e8')))
            where true
          union
          (
          select distinct 
              ref_14.c_g_ius6q as c_rolc9
            from 
              v_bj9vgampt as ref_14
            where (ref_14.c_gfngub2 like 'a%')
          )))
      limit 113))
);
```
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1), server 11.2-YB-2.25.0.0-b0)
yb_main=> 
```
init.sql:
[init.sql.txt](https://github.com/user-attachments/files/17177849/init.sql.txt)

## Error Log
postgresql-2024-09-29_000000.log
```

-1/x-1/x-1/x-1/x-1/x-1/x-1/x-1/x-1/x-1/xI0929 04:59:33.388792 62596 env_posix.cc:1499] Using memory limit from sysinfo(): 540649799680
I0929 04:59:33.389024 62596 mem_tracker.cc:213] Root memory limit is 459552329728
I0929 04:59:33.391582 62596 thread_pool.cc:178] Starting thread pool { name: pggate_ybclient max_workers: 1024 }
I0929 04:59:33.394086 62596 pg_client.cc:387] Using TServer host_port: 10.1.3.21:9100
I0929 04:59:33.401652 62596 pg_client.cc:400] Session id 6030: Session id acquired. Postgres backend pid: 62596
I0929 04:59:33.426513 62596 backoff_waiter.cc:130] Database 13260 is not ready in Yugabyte shared memory - started
I0929 04:59:33.427069 62596 backoff_waiter.cc:133] Database 13260 is not ready in Yugabyte shared memory - completed: OK
I0929 04:59:33.517287 62605 env_posix.cc:1499] Using memory limit from sysinfo(): 540649799680
I0929 04:59:33.517526 62605 mem_tracker.cc:213] Root memory limit is 459552329728
I0929 04:59:33.520179 62605 thread_pool.cc:178] Starting thread pool { name: pggate_ybclient max_workers: 1024 }
I0929 04:59:33.522732 62605 pg_client.cc:387] Using TServer host_port: 10.1.3.21:9100
I0929 04:59:33.530468 62605 pg_client.cc:400] Session id 6031: Session id acquired. Postgres backend pid: 62605
I0929 04:59:33.551010 62605 backoff_waiter.cc:130] Database 13260 is not ready in Yugabyte shared memory - started
I0929 04:59:33.551579 62605 backoff_waiter.cc:133] Database 13260 is not ready in Yugabyte shared memory - completed: OK
I0929 04:59:33.634424 62614 env_posix.cc:1499] Using memory limit from sysinfo(): 540649799680
I0929 04:59:33.634668 62614 mem_tracker.cc:213] Root memory limit is 459552329728
I0929 04:59:33.637295 62614 thread_pool.cc:178] Starting thread pool { name: pggate_ybclient max_workers: 1024 }
I0929 04:59:33.639839 62614 pg_client.cc:387] Using TServer host_port: 10.1.3.21:9100
I0929 04:59:33.647171 62614 pg_client.cc:400] Session id 6032: Session id acquired. Postgres backend pid: 62614
I0929 04:59:34.192629 62614 backoff_waiter.cc:130] Database 16658 is not ready in Yugabyte shared memory - started
I0929 04:59:34.193186 62614 backoff_waiter.cc:133] Database 16658 is not ready in Yugabyte shared memory - completed: OK
TRAP: FailedAssertion("!(!bms_is_empty(unbatchablerelids) || bms_equal(pclause_batched_inner_attnos, batched_inner_attnos))", File: "../../../../../../../src/postgres/src/backend/optimizer/path/indxpath.c", Line: 783)
2024-09-29 04:59:34.949 UTC [71] WARNING:  server process (PID 62614) was terminated by signal 6: Aborted
2024-09-29 04:59:34.949 UTC [71] DETAIL:  Failed process was running: select  
	    cast((cast(cast(null as "time") as "time") - cast(cast(null as "interval") as "interval")) as "time") as c_s8mz_2917, 
	    ref_0.c_v85ohw8yd as c_k4_2918, 
	    pg_catalog.jsonb_delete(
	      cast(cast(null as jsonb) as jsonb), 
	      cast(pg_catalog.lpad(
	        cast(case when (cast((cast(cast(null as circle) as circle) >= cast(cast(null as circle) as circle)) as bool)) then ref_0.c_gfvd6rqp else (select c_y5m2sv_ from t_buksrm7ac3 order by c_y5m2sv_ limit 1 offset 2)
	             end
	           as text), 
	        cast((abs(1281403065%4294967296)-2147483648) as int4), 
	        cast(ref_0.c_j36 as text)) as text)) as c_b9aivs_2919, 
	    ref_0.c_cr_hoi as c_tem35tdczz_2920, 
	    cast((abs(coalesce(
	      2005426017, 
	      1122787506
	      )%4294967296)-2147483648) as int4) as c__q_2921, 
	    ref_0.c_xrgtmyt as c_jz1gubpxk_2922, 
	    ref_0.c_d0 as c_dz_2923, 
	    ref_0.c_v85ohw8yd as c_qgjh_2924, 
	    cast((cast(cast(null as numrange) as numrange) &> cast(cast(null as numrange) as numrange)) as b
I0929 04:59:39.958288 62609 poller.cc:69] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:78): Scheduler is shutting down (system error 108)
I0929 04:59:39.958267 62598 poller.cc:69] Poll stopped: Service unavailable (yb/rpc/scheduler.cc:78): Scheduler is shutting down (system error 108)
```
### About Us
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in Yugabyte that may lead to database crashes.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.
