### ISSUE TITLE
[yugabyted] --advertise_address=0.0.0.0 not change yugabyted.conf inside docker

### ISSUE THREAD

**Issue by zeinali-ali** [yugabyte/yugabyte-db#24288]
### Description

I'm using below docker-compose config to run yugabyte, it seems `--advertise_address=0.0.0.0` not working on version `2.23.0.0-b710` and the `advertise_address` field inside `yugabyted.conf` is still `127.0.0.1` while when I down-grade to version `2.19.3.0-b140` it work without problem.

```
services:
  yugabyte:
    image: yugabytedb/yugabyte:latest
    command: ["/home/yugabyte/bin/yugabyted",
              "start",
              "--advertise_address=0.0.0.0",
              "--base_dir=/home/yugabyte/yb_data",
              "--background=false",
              "--ysql_enable_auth=true",
              "--use_cassandra_authentication=true"]
    ports:
      - "7000:7000"
      - "9000:9000"
      - "5433:5433"
      - "9042:9042"
    volumes:
      - yb-data:/home/yugabyte/yb_data
```

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.

**Comment by ddorian** [comment]
Can you replicate this with a fresh start? Maybe it's a bad upgrade from 2.19 -> 2.23 (upgrades aren't supported on these versions)

I can change the advertise address usually (I don't use 127.0.0.1)

**Comment by ddorian** [comment]
Looks like it was changed in this issue/commit:

https://github.com/yugabyte/yugabyte-db/issues/18580

https://github.com/yugabyte/yugabyte-db/commit/cade0a8688fea889f1595bfa0a15d61124849f0d

**Comment by ddorian** [comment]
cc @FranckPachot what ip should they use in this scenario?

**Comment by FranckPachot** [comment]
Hey @zeinali-ali, for Docker, you can remove `--advertise_address=0.0.0.0`. Without it, Docker listens to the hostname interface, which is the correct one to be exposed by `ports`. If you run `ysqlsh` within the container, then set `PGHOST=$(hostname)`.
Before this commit, 0.0.0.0 listened to all interfaces, which should be the correct behavior. However, because the UI also uses this value, it has been replaced with listening to localhost only.

**Comment by alberk8** [comment]
This works and if want to use FQDN then uncomment the hostname.   The container_name also registered in Docker internal DNS.

```
services:
  yugabyte:
    image: yugabytedb/yugabyte:latest
    restart: unless-stopped
    container_name: yugabyte
    #hostname: yugabyte.company.com
    ports:
      - 7000:7000
      - 9000:9000
      - 15433:15433
      - 5433:5433
      - 9042:9042
    command: ["/home/yugabyte/bin/yugabyted", "start", "--base_dir=/home/yugabyte/yb_data", "--advertise_address=yugabyte", "--background=false"]
    volumes:
      - ./data:/home/yugabyte/yb_data
```
