### ISSUE TITLE
[YSQL] `bttextcmp` in where clause may lead to incorrect result

### ISSUE THREAD

**Issue by r33s3n6** [yugabyte/yugabyte-db#24386]
### Version:
```
commit 230793715fbd7587ec553b9ab3f23cb8ac40db76 (HEAD -> master, origin/master, origin/HEAD)

PostgreSQL 11.2-YB-2.25.0.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 17.0.6 (https://github.com/yugabyte/llvm-project.git 9b881774e40024e901fc6f3d313607b071c08631), 64-bit
```

## Reproduce
```sql
create table t1 ( 
  c1 int4 ,
  primary key(c1)
);

alter table t1 add column c3 text;
insert into t1 values (-13, 'haa');

SELECT
  ref_1.c1,
  ref_1.c3,
  pg_catalog.bttextcmp(
      cast(ref_1.c3 as text), 
      cast('oaaaaaa' as text)),
  (ref_1.c1 between pg_catalog.bttextcmp(
      cast(ref_1.c3 as text), 
      cast('oaaaaaa' as text)) and ref_1.c1)
FROM
  t1 as ref_1
WHERE
  (ref_1.c1 between pg_catalog.bttextcmp(
      cast(ref_1.c3 as text), 
      cast('oaaaaaa' as text)) and ref_1.c1) 
;
```

output:
```
 c1  | c3  | bttextcmp | ?column? 
-----+-----+-----------+----------
 -13 | haa |        -7 | f
(1 row)
```
Note that the fourth column corresponds to the WHERE clause; if it evaluates to false, the record should not appear in the result set. The result is unstable, so try executing it multiple times.

### Build
The build is performed in the AlmaLinux 8 environment, and name the compressed file as `yb.tar.gz`.
```bash
git clone git@github.com:yugabyte/yugabyte-db.git
cd yugabyte-db
./yb_build.sh asan
./yb_release --skip_build --build_archive --build_root /home/yugabyte-db/build/asan-clang17-dynamic --no_odyssey --no_yugabyted_ui
```
#### Create Docker Image and Container
```bash
docker build -t my_yugabyte:latest .
export YB_SUBNET=10.1.3
docker compose up -d
```
Dockerfile
```Dockerfile
FROM yugabytedb/yugabyte:latest

RUN rm -rf /home/yugabyte/*
COPY ./yb.tar.gz /tmp
RUN tar xf /tmp/yb.tar.gz -C /home/yugabyte --strip-components 1
```
docker-compose.yaml
```yaml
x-service-defaults: &service_defaults
  image: my_yugabyte:latest
  tmpfs:
    - /tmp
  environment:
    SERVICE_5433_NAME: ysql
    SERVICE_9042_NAME: ycql
    SERVICE_6379_NAME: yedis
    SERVICE_7000_NAME: yb-master
    SERVICE_9000_NAME: yb-tserver
    ASAN_OPTIONS: detect_leaks=0:use_sigaltstack=false

services:
  master:
    <<: *service_defaults
    volumes:
      - master-data-1:/mnt/master
    command:
      - "/home/yugabyte/bin/yb-master"
      - "--fs_data_dirs=/mnt/master"
      - "--master_addresses=master:7100"
      - "--rpc_bind_addresses=master:7100"
      - "--replication_factor=1"
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.11

  tserver1:
    <<: *service_defaults
    volumes:
      - tserver-data-1:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver1:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.21

  tserver2:
    <<: *service_defaults
    volumes:
      - tserver-data-2:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver2:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.22

  tserver3:
    <<: *service_defaults
    volumes:
      - tserver-data-3:/mnt/tserver
    command:
      - "/home/yugabyte/bin/yb-tserver"
      - "--fs_data_dirs=/mnt/tserver"
      - "--enable_ysql"
      - "--rpc_bind_addresses=tserver3:9100"
      - "--tserver_master_addrs=master:7100"
    depends_on:
      - master
    networks:
      yb-net:
        ipv4_address: ${YB_SUBNET}.23

networks:
  yb-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: ${YB_SUBNET:?please provide subnet range like `10.3.1`}.0/24
          gateway: ${YB_SUBNET}.1

volumes:
  master-data-1:
  tserver-data-1:
  tserver-data-2:
  tserver-data-3:
```

**About Us**
We are the BASS team from the School of Cyber Science and Technology at Beihang University. Our main focus is on system software security, operating systems, and program analysis research, as well as the development of automated program testing frameworks for detecting software defects. Using our self-developed database vulnerability testing tool, we have identified the above-mentioned vulnerabilities in Yugabyte that may lead to database logic bug.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [X] I confirm this issue does not contain any sensitive information.
