### ISSUE TITLE
[YSQL] Connection Manager disconnects extended-protocol queries from Elixir / Postgrex

### ISSUE THREAD

**Issue by munjalpatel** [yugabyte/yugabyte-db#26041]
### Description

**Environment / Versions**
	•	YugabyteDB: 2.25.0.0-b489
	•	Elixir: 1.18.1 (OTP 27)
	•	Postgrex: 0.20.0
	•	Odyssey: Enabled via --enable_ysql_conn_mgr=true

I’m running a local setup with YugabyteDB 2.25, configured to use Odyssey as the connection manager.
When I attempt a simple query via a GUI client (e.g. Beekeeper Studio), everything works. But if I run the same query from Elixir’s [Postgrex](https://github.com/elixir-ecto/postgrex) (which uses the extended query protocol), Odyssey immediately disconnects the session.

**Symptoms**

In Elixir / Postgrex:
```elixir
{:ok, pid} = Postgrex.start_link(
  hostname: "localhost",
  port: 5433,
  username: "myapp",
  password: "myapp",
  database: "myapp"
  # Also tried passing prepare: :unnamed with the same result
)

Postgrex.query(pid, "SELECT * FROM pg_catalog.pg_database", [])
```

Returns:
```elixir
{:error,
 %DBConnection.ConnectionError{
   message: "tcp recv (idle): closed",
   severity: :error,
   reason: :error
 }}
```

Odyssey logs show:
```
(remote client) Parse
(remote client) Describe
...
operator was not prepared by this client
...
server disconnected (read/write error): Resource temporarily unavailable
```

In Beekeeper Studio (or other simple-protocol clients):
The same query, SELECT * FROM pg_catalog.pg_database, succeeds with no issues:
```
(remote client) Query
(main) RowDescription
(main) DataRow
(main) CommandComplete
(main) ReadyForQuery
...
```

---

**Attempted Workarounds**
1. prepare: :unnamed
I tried disabling named prepared statements in Postgrex, but Odyssey still disconnects as soon as the driver issues the Parse / Describe messages.

2. Confirmed direct connections
Bypassing Odyssey and connecting directly to the native YSQL port works fine for both simple and extended protocols.

---

**Steps to Reproduce**
Below is a minimal setup using Docker Compose, along with an setup.sql file and the Odyssey flagfile (ydb.conf) that enables the YSQL connection manager. This should make it easy for anyone to replicate the issue.

**docker-compose.yaml**
```yaml
version: '3.7'
services:
  db:
    image: yugabytedb/yugabyte:2.25.0.0-b489
    container_name: db
    restart: always
    command: >
      bin/yugabyted start
        --listen=db
        --background=false
        --tserver_flags=flagfile=/ydb.conf
        --base_dir=/home/yugabyte/yb_data
        --callhome=false
    ports:
      - "5433:5433"
      - "7003:7000"
      - "15433:15433"
    volumes:
      - ./ydb.conf:/ydb.conf
      - ./data:/home/yugabyte/yb_data
    healthcheck:
      test: ["CMD-SHELL", "postgres/bin/pg_isready -U yugabyte -h db"]
      interval: 1s
      timeout: 60s
      retries: 65
      start_period: 1s
    networks:
      - db

  db-setup:
    image: yugabytedb/yugabyte:2.25.0.0-b489
    container_name: db-setup
    command: ["bin/ysqlsh", "-h", "db", "-U", "yugabyte", "-f", "/setup.sql"]
    environment:
      - PGPASSWORD=yugabyte
    volumes:
      - ./setup.sql:/setup.sql
    networks:
      - db
    depends_on:
      db:
        condition: service_healthy

networks:
  db:
    driver: bridge
```

**ydb.conf**
```conf
--enable_ysql_conn_mgr=true
--allowed_preview_flags_csv=enable_ysql_conn_mgr
--ysql_conn_mgr_log_settings=log_debug,log_config,log_session,log_query,log_stats
```

**setup.sql**
```sql
CREATE ROLE myapp WITH LOGIN PASSWORD 'myapp' NOSUPERUSER CREATEDB CREATEROLE;
CREATE DATABASE myapp;
ALTER DATABASE myapp OWNER TO myapp;

REVOKE CONNECT ON DATABASE myapp FROM PUBLIC;
GRANT CONNECT ON DATABASE myapp TO myapp;
```

**Start everything:**
```
docker-compose up -d
# Wait until db-setup completes
```

**Test from Elixir:**
```bash
mix new pgtest
cd pgtest

# In mix.exs, add: {:postgrex, "~> 0.20"}

mix deps.get
iex -S mix
```

**Then in IEx:**
```elixir
{:ok, pid} = Postgrex.start_link(
  hostname: "localhost",
  port: 5433,
  username: "myapp",
  password: "myapp",
  database: "myapp"
)

Postgrex.query(pid, "SELECT * FROM pg_catalog.pg_database", [])
```

**You’ll see:**
```elixir
[error] Postgrex.Protocol (#PID<...>) disconnected:
** (DBConnection.ConnectionError) tcp recv (idle): closed
```

Meanwhile, Odyssey logs show it disconnecting on Parse / Describe.

### Issue Type

kind/bug

### Warning: Please confirm that this issue does not contain any sensitive information

- [x] I confirm this issue does not contain any sensitive information.
