### ISSUE TITLE
The email for travis notifications is mis-configured

### ISSUE THREAD

**Issue by maysamyabandeh** [YugaByte/yugabyte-db#40]
https://github.com/YugaByte/yugabyte-db/blob/master/.travis.yml#L41
```
notifications:
    email:
      - leveldb@fb.com
    webhooks:
```
