### ISSUE TITLE
[YEDIS] yb-ctl/yugabyted should not bind on 6379 till YEDIS is explicitly turned on even if this means a restart

### ISSUE THREAD

**Issue by schoudhury** [yugabyte/yugabyte-db#4057]
yb-ctl & yugabyted bind on 6379 port even if there is no intent on the part of the user to start YEDIS explicitly using the `setup_redis` command. This is leading to poor user experience whenever a user has a redis-server already running on his/her local machine on the same 6379 port. Now add this to poor error handling where such a port conflict doesn't get propagated back to the user (https://github.com/yugabyte/yugabyte-db/issues/3746).

yb-ctl/yugabyted should not bind on 6379 till YEDIS is explicitly turned on even if this means a restart is needed.

**Comment by corford** [comment]
For anyone running redis and yugabytedb in dev with docker-compose the workaround is a hidden(?) flag to `yugabyted` that forces yedis to listen on a different port:  `--tserver_flags='redis_proxy_bind_address=127.0.0.1:54444'` (thanks to YB team on slack for the hint):

Example docker-compose:

```
version: "3.7"
services:
  redis:
    container_name: redis
    restart: on-failure:3
    image: redis:5.0.7-alpine
    network_mode: host
  yugabytedb:
    container_name: yugabytedb
    restart: on-failure:3
    image: yugabytedb/yugabyte:2.1.6.0-b17
    network_mode: host
    volumes:
      - type: volume
        source: yugabytedb-data
        target: /home/yugabyte/var
        volume:
          nocopy: true
    command: "bin/yugabyted start --daemon=false --ui=false --tserver_flags='redis_proxy_bind_address=127.0.0.1:54444'"

volumes:
  yugabytedb-data:

```
