### ISSUE TITLE
Docs specify incorrect storageClass parameter for Helm chart

### ISSUE THREAD

**Issue by danports** [yugabyte/yugabyte-db#4631]
[The docs](https://docs.yugabyte.com/latest/deploy/kubernetes/single-zone/oss/helm-chart/#storage-class) say you should `--set persistentVolume.storageClass=` but the chart `values.yaml` has this:
```yaml
storage:
  ephemeral: false  # will not allocate PVs when true
  master:
    count: 2
    size: 10Gi
    storageClass: standard
  tserver:
    count: 2
    size: 10Gi
    storageClass: standard
```
Needless to say, setting `persistentVolume.storageClass` on a Helm release does nothing.
