### ISSUE TITLE
[YSQL] Segmentation fault on DROP DATABASE

### ISSUE THREAD

**Issue by Bessonov** [yugabyte/yugabyte-db#5411]
I get following message:

```
# drop database hasura;
WARNING:  terminating connection because of crash of another server process
DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
HINT:  In a moment you should be able to reconnect to the database and repeat your command.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```
The public schema has two empty tables with a relation between them. There are some schemas for hasura:

```
# select schema_name from information_schema.schemata;
    schema_name     
--------------------
 pg_catalog
 pg_toast
 public
 information_schema
 hdb_catalog
 hdb_views
```

```
  yugabyte:
    image: yugabytedb/yugabyte:2.2.0.0-b80
    ports:
      - "127.0.0.1:$YB_MASTER_WEB_PORT:7000"
      - "127.0.0.1:$YB_SERVER_WEB_PORT:9000"
      - "127.0.0.1:$YB_POSTGRES_PORT:5433"
      - "127.0.0.1:$YB_CASSANDRA_PORT:9042"
      - "127.0.0.1:$YB_REDIS_PORT:6379"
    command:
      - bin/yugabyted
      - start
      - --daemon=false
```

Docker logs are empty:
```
Starting yugabyted...
✅ System checks
```

Is there any diagnostic I can opt-in to help?
