### ISSUE TITLE
[Grafana_Dashboard]Listing all master and tserver nodes in both panels

### ISSUE THREAD

**Issue by ricemaster** [yugabyte/yugabyte-db#5606]
Hi guys,

I don't know if it's OK to open an issue here for [YugabyteDB Dashboard for Grafana](https://grafana.com/grafana/dashboards/12620). I'm sorry for all the inconvenience.

I'm using Revision 2 of YugabyteDB Dashboard in Grafana v7.1.5 with Prometheus v2.20.1 on CentOS7. 

It's a 6-node cluster, 3 master nodes and 3 tserver nodes. I deployed the cluster following the instruction in [Manual deployment](https://docs.yugabyte.com/latest/deploy/manual-deployment/). 

My `prometheus.yml` is like below:
```
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# YugaByte DB configuration to scrape Prometheus time-series metrics
scrape_configs:
  - job_name: 'yugabytedb'
    metrics_path: /prometheus-metrics

    static_configs:
      - targets: ['10.211.55.101:7000', '10.211.55.102:7000', '10.211.55.103:7000']
        labels:
          group: 'yb-master'

      - targets: ['10.211.55.104:9000', '10.211.55.105:9000', '10.211.55.106:9000']
        labels:
          group: 'yb-tserver'
```

And in the YugabyteDB Dashboard, all 6 nodes are shown in both `Master Node Status` panal and `Tserver Node Status` panal.
<img width="1719" alt="dashboard" src="https://user-images.githubusercontent.com/10449002/92318197-5b141180-f03b-11ea-976e-7c777346bb87.png">

I don't know it's an issue, or I did something wrong. It would be super apprieciated if someone could help me get out of this.

**Comment by kmuthukk** [comment]
cc: @bhavin192 ^^ for help with respect to the grafana question.

@ricemaster -- for VM or baremetal deployment, you can run yb-master processes on the same nodes as yb-tserver processes. The yb-master processes are not very resource intensive. For example, if you have 6-similar nodes, you can run yb-tserver on all 6-nodes and yb-master on just 3 of them. [The number of yb-master processes should be same as the replication factor.]

**Comment by ricemaster** [comment]
@kmuthukk Got it! Thank you for the advice. That's really helpful.

**Comment by bhavin192** [comment]
@ricemaster it's a known issue and I don't think there is anything wrong in your configuration. With the above dashboard you will need more scrape configuration to make all the panels work. I will get back to you with a scrape configuration which you can test.
Ref: https://github.com/yugabyte/charts/blob/ea342e49de39732bffcce338ac0acfb9a9e60b42/stable/yugabyte/values.yaml#L149-L169 (common for all the targets)
Ref: https://github.com/yugabyte/charts/blob/ea342e49de39732bffcce338ac0acfb9a9e60b42/stable/yugabyte/templates/tserver-servicemonitor.yaml
These are not exactly in the promethus.yaml format.

**Comment by bhavin192** [comment]
@ricemaster you can try this configuration to get all the panels working. 
```yaml
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 5 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# YugaByte DB configuration to scrape Prometheus time-series metrics
scrape_configs:
  - job_name: "yugabytedb"
    metrics_path: /prometheus-metrics
    relabel_configs:
      - target_label: "node_prefix"
        replacement: "cluster-1"
    metric_relabel_configs:
      # Save the name of the metric so we can group_by since we cannot by __name__ directly...
      - source_labels: ["__name__"]
        regex: "(.*)"
        target_label: "saved_name"
        replacement: "$1"
      # The following basically retrofit the handler_latency_* metrics to label format.
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
        target_label: "server_type"
        replacement: "$1"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(.*)"
        target_label: "service_type"
        replacement: "$2"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
        target_label: "service_method"
        replacement: "$3"
      - source_labels: ["__name__"]
        regex: "handler_latency_(yb_[^_]*)_([^_]*)_([^_]*)(_sum|_count)?"
        target_label: "__name__"
        replacement: "rpc_latency$4"

    static_configs:
      - targets: ["10.211.55.101:7000", "10.211.55.102:7000", "10.211.55.103:7000"]
        labels:
          group: "yb-master"
          export_type: "master_export"

      - targets: ["10.211.55.104:9000", "10.211.55.105:9000", "10.211.55.106:9000"]
        labels:
          group: "yb-tserver"
          export_type: "tserver_export"

      - targets: ["10.211.55.104:12000", "10.211.55.105:12000", "10.211.55.106:12000"]
        labels:
          group: "ycql"
          export_type: "cql_export"

      - targets: ["10.211.55.104:13000", "10.211.55.105:13000", "10.211.55.106:13000"]
        labels:
          group: "ysql"
          export_type: "ysql_export"

      - targets: ["10.211.55.104:11000", "10.211.55.105:11000", "10.211.55.106:11000"]
        labels:
          group: "yedis"
          export_type: "redis_export"
```
