### ISSUE TITLE
Ability to view SQL metrics in Istio when running against YB's SQL port

### ISSUE THREAD

**Issue by iSignal** [yugabyte/yugabyte-db#5903]
Similar to the metrics shown in https://blog.yugabyte.com/using-envoy-proxys-postgresql-tcp-filters-to-collect-yugabyte-sql-statistics/, would be good to get similar insights / metrics from a Istio enabled namespace with yugabytedb running for queries against the SQL 5433 port.

@chirag-yb

**Comment by bhavin192** [comment]
I was able to get this working with following EnvoyFilter, it modifies the Envoy sidecar's configuration as shown in above blog post.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: postgres-stats
spec:
  workloadSelector:
    labels:
      app: yb-tserver
  configPatches:
  - applyTo: NETWORK_FILTER
    match:
      context: SIDECAR_INBOUND  # will match outbound listeners in all sidecars
      listener:
        portNumber: 5433
        filterChain:
          filter:
            name: "envoy.tcp_proxy"
    patch:
      operation: INSERT_BEFORE
      value:
        # This is the full filter config including the name and config or typed_config section.
        name: "envoy.filters.network.postgres_proxy"
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.network.postgres_proxy.v3alpha.PostgresProxy
          stat_prefix: ysql
```

We also need to annotate all the yb-tserver pods with,

```yaml
sidecar.istio.io/statsInclusionPrefixes: postgres,cluster_manager,listener_manager,server,cluster.xds-grpc
```

This basically exposes the stats with postgres prefix along with other default ones.

Once done, one can view the metrics in Prometheus, these are prefixed with `istio_postgres`.
