### ISSUE TITLE
[docs] Kafka / YSQL example

### ISSUE THREAD

**Issue by ddorian** [yugabyte/yugabyte-db#5973]
The example is pretty simple. We can use the regular PostgreSQL JDBC connector
Example config:
```
apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaConnector"
metadata:
  # connector name
  name: "output-snk-users-json-001"
  labels:
    # kafka connect [cluster] name
    strimzi.io/cluster: kafka-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  key.converter: "org.apache.kafka.connect.storage.StringConverter"
  value.converter: "org.apache.kafka.connect.json.JsonConverter"
  tasksMax: 2
  config:
    connection.url: "jdbc:postgresql://127.0.0.1:5433/testedb?user=user&password=password"
    connection.attempts: "2"
    topics: "src-users-json"
    auto.create: "true"
    auto.evolve: "true"
    insert.mode: "upsert"
    pk.fields: "id"
    pk.mode: "record_key"
    batch.size: "1500"
```
