### ISSUE TITLE
[DocDB] Expose a "total memory available" metric in prometheus/node exporter

### ISSUE THREAD

**Issue by brad-plumewifi** [yugabyte/yugabyte-db#7271]
Jira Link: [DB-2154](https://yugabyte.atlassian.net/browse/DB-2154)
It would be useful to expose the amount of total memory available on the VM so that we can derive a "total memory used" graph. mem_free is partially useful, but it would be useful to see what's used relative to the total available on the system

Please export "mem_total" as a function of the total available memory on the VM so I can write a query to derive mem_used, or, export a separate "mem_used" metric as well.  Either way :)

```
memory_usage:
  metric: ""
  function: "avg"
  operator: "/ 1073741824"
  filters:
    saved_name: "node_memory_Cached|node_memory_Buffers|node_memory_MemFree"
  group_by: "saved_name"
  layout:
    title: "Memory Usage"
    xaxis:
      type: "date"
    yaxis:
      alias:
        "node_memory_Cached": "cached"
        "node_memory_Buffers": "buffered"
        "node_memory_MemFree": "free"
      ticksuffix: "&nbsp;GB"
```

[DB-2154]: https://yugabyte.atlassian.net/browse/DB-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
