### ISSUE TITLE
Enhancements to the yugabyte-platform-operator deployment

### ISSUE THREAD

**Issue by bhavin192** [yugabyte/yugabyte-db#7282]
- [ ] The Helm based operator deployment should have appropriate resource requirements. These were removed [here](https://github.com/yugabyte/yugabyte-platform-operator/commit/bc010fdd7f9beb0e6edaf278800c56d4ec5f453f#diff-ce0d597a9e5f20a8fe61c3ba5e6185a6b90cfef2c00bb5b5ef3e97b15b79f480).
- [ ] Add an `app` label to the deployment, something like `app=yugabyte-platform-operator` that way it is easy to find the pod.
- [ ] Update the `ocpCompatibily.enabled=true`, `rbac.create=false` and the `image.repository` in `helm-charts/values.yaml`. That way user can create an instance of YBPlatform with following YAML.
  ```yaml
  apiVersion: yugabyte.com/v1alpha1
  kind: YBPlatform
  metadata:
    name: ybplatform-sample
  spec: {}
  ```
