### ISSUE TITLE
[Platform] [UI] Fix Sample app command for ycql  when TLS enabled for k8s universe

### ISSUE THREAD

**Issue by gurushant-yb** [yugabyte/yugabyte-db#7693]
Related issue is https://github.com/yugabyte/yugabyte-db/issues/6615
User should be able to pass --ssl_cert in sample application run command for YSQL and YCQL

Following is sample command, user can copy it from UI:
<img width="1049" alt="Screenshot 2021-03-17 at 2 25 22 PM" src="https://user-images.githubusercontent.com/79436143/111440765-aca90180-872c-11eb-9587-0e9ba0cab6fe.png">

**Comment by gurushant-yb** [comment]
We need to create following manifest automatically for the user to run the sample apps on k8 cluster:
```
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: opaque
data:
  root.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFakNDQWZxZ0F3SUJBZ0lHQVhnZGg1cXRNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1EWXhIakFjQmdOVkJBTU0KRlhsaUxXUmxkaTF3ZFhCd2VTMW1iMjlrTFhSc2N6RVVNQklHQTFVRUNnd0xaWGhoYlhCc1pTNWpiMjB3SGhjTgpNakV3TXpFd01Ua3dOVEk1V2hjTk1qSXdNekV3TVRrd05USTVXakEyTVI0d0hBWURWUVFEREJWNVlpMWtaWFl0CmNIVndjSGt0Wm05dlpDMTBiSE14RkRBU0JnTlZCQW9NQzJWNFlXMXdiR1V1WTI5dE1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW8wUlNOWmdRQkswL1J2K09uNCtQWjNKazZGNzFub0c1bXhmQgpoSURuSjFrd2p1QnlNbitaSVlvZkczTDY4L0RtS29scmQrbHdKblhPaTJRSEpFQUg0UHBGTnBWdU5jemlNaVJ3Cks3dW1FUHBBMFRtVUVueWJ6UytuMmo5Uit6dVRGRGNlc1BtTVZrRnIwbzc4ZzdDa1pjMmhaM2hhZVpBbzY5cWYKSm81c2VhUUp2RmlObXlmUlhsd3RUaE1uTmdJTVlqMU41bzc5enFWVDJIZ0d0OXJVdFhDZDlvNDRCaXhzM1VHUgpucWg4RWNINmFnMjhCdDArRE9SazUrbmtIei93Qms3SGlrNkY3cmtCWERlcytoMDlVekU0TzBhd21TdUZVbmtoCnhidDdqQjlwaWpKdmV6THRtZnhvR1BGMmFYbUU1WjlWMElyNDluaEdaL05OanV2Zk53SURBUUFCb3lZd0pEQVMKQmdOVkhSTUJBZjhFQ0RBR0FRSC9BZ0VCTUE0R0ExVWREd0VCL3dRRUF3SUM1REFOQmdrcWhraUc5dzBCQVFzRgpBQU9DQVFFQVczY256MVAxbUtZdHRQNk9pMnlkY2F0K3hjN1AzSkJDSXVCZ0Y2S3lyOFMrL0I2WjlycGN6Z1ZSCm0yREhZR2RjU2hFWHNDU0pQY3BEaUlSMGdrNzc5cWJ5aS8xVXp2bDN0aVNqTzdCTFNjOWprSWlyL3VVeXREdEcKbkpIanMyWDd0OHNMKzdWaVZnSHNYQjNMSmpyVUl6b25aUUQxS3hGc2paZ2pyWUl4RUN4WWgvUTIwd3k2K1V4eAp6OE8zTmFvbHUzTzJGdkYxNEUwV1R5RmdxYjFLT3pPMStwTGdEY1B6SG1sSGpyOEZqNjJUZzdBZDNLUnExMFRrCk5IcHFPaXJhODcyMDE2YTlRRlZybXFPY2ZVWVZoc0FxSGd4SkFPdXFscnExMlU5UUgzc3ViZ0liSkRUYnNGRFkKNC9TeUlkS0FjYmFZQkpNb1dOZEdxa0tWeXFJMjRRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=

---

apiVersion: v1
kind: Pod
metadata:
  name: yb-sample-apps
spec:
  containers:
    - name : yb-sample-apps
      image: yugabytedb/yb-sample-apps
      args:
      - --workload
      - CassandraKeyValue
      - --nodes
      - yb-tserver-2.yb-tservers.yb-dev-puppy-food-tls.svc.cluster.local:9042,yb-tserver-4.yb-tservers.yb-dev-puppy-food-tls.svc.cluster.local:9042,yb-tserver-1.yb-tservers.yb-dev-puppy-food-tls.svc.cluster.local:9042,yb-tserver-3.yb-tservers.yb-dev-puppy-food-tls.svc.cluster.local:9042,yb-tserver-0.yb-tservers.yb-dev-puppy-food-tls.svc.cluster.local:9042 
      - --ssl_cert
      - /home/root.crt
      volumeMounts:
        - name: config 
          mountPath: /home
          readOnly: true     

  volumes:
    - name: config
      secret:
        secretName: secret
```
