### ISSUE TITLE
The slowness when querying system tables

### ISSUE THREAD

**Issue by p-null** [yugabyte/yugabyte-db#7745]
Hi, open this pr to report and track the slowness/timeout issue when testing hasura + yb.

I am running yb(2.5.3.1) on a 4 node k8s cluster (20 cores and 60 gb) with the following (related) values:
```
resource:
  master:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  tserver:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi

replicas:
  master: 3
  tserver: 3
```

The connected database only has 1 table with 3 records, having columns of id(int), name(text).
When accessing hasura console (the UI), some queries will be executed to display the table/schema info of the database. However i consistently get failing/timeout errors at the frontend. 

By analyzing networking requests sent from frontend, i was able to locate the queries that caused the timeout. 
The following is one of the queries that hasura console will execute. Here is one of them:

First exec to pod:
```
$ kubectl exec --namespace yugabyte -it yb-tserver-0 -- /home/yugabyte/bin/ysqlsh -U internal_service -h yb-tserver-0.yb-tservers.yugabyte
```
Then
```
yugabyte=# SELECT column_name, table_name, is_generated, is_identity, identity_generation FROM information_schema.columns where table_schema = 'public';
 column_name | table_name | is_generated | is_identity | identity_generation
-------------+------------+--------------+-------------+---------------------
(0 rows)
Time: 110913.507 ms (01:50.914)
```

The lantency of running normal graohql queries on application tables is fine. The timeout/slowness occurs eveytime accessing the data tab on the hasura UI. I also would like to mention this point here: accessing the data tab is a common task and everytime one clicks a new schema/table, the hasura UI will execute the above query. Therefore the slowness here pretty much makes the data tab unusable.
